### ISSUE TITLE
Add step back/continue back

### ISSUE THREAD

**Issue by Maijin** [rizinorg/cutter#1022]
Add step back/continue back in emulation mode.

**Comment by xarkes** [comment]
Removing from Debugger project as it is only for emulation.

**Comment by XVilka** [comment]
@xarkes actually no, it should work for debugging too, it was the idea of the reversible debugger in radare2 - it shares the code between ESIL and native debug

**Comment by xarkes** [comment]
I know, but it is not necessary nor important for having a working Debugger. We will implement that when the debugger will actually work.

**Comment by ITAYC0HEN** [comment]
A debugger is actually working now :)
