### ISSUE TITLE
Generate templates as in https://radare.gitbooks.io/radare2book/plugins/python.html

### ISSUE THREAD

**Issue by Maijin** [rizinorg/cutter#1025]
```
def mycpu(a):
 def assemble(s):
     return [1, 2, 3, 4]

 def disassemble(buf):
     try:
         opcode = get_opcode(buf)
         opstr = optbl[opcode][1]
         return [4, opstr]
     except:
         return [4, "unknown"]

print("Registering MYCPU disasm plugin...")
print(r2lang.plugin("asm", mycpu))
```

**Comment by ITAYC0HEN** [comment]
What do you mean exactly?

**Comment by xarkes** [comment]
The example is for r2lang, indeed it would be very useful but I think we need to integrate r2lang first :)
Now we could provide templates for making plugins directly from Cutter, but I'm not sure if that's very relevant. Maybe once we have a proper python console?

**Comment by ITAYC0HEN** [comment]
> Maybe once we have a proper python console?

yeah, it should be quite a quick implementation, right? ;)
