### ISSUE TITLE
r2 console JSON output broken

### ISSUE THREAD

**Issue by qjerome** [rizinorg/cutter#1051]
**Environment information**
* Operating System: Linux
* Cutter version: 1.7.3
* File format: any

**Describe the bug**
The r2 commands **.*j** (supposed to return JSON) executed from a r2pipe do not return JSON deserializable output anymore.

**To Reproduce**
1. Open Cutter from a terminal to be able to read stdout/stderr
2. Go to r2 console lower left corner, paste and execute #!pipe python3 -c "import r2pipe; r2 = r2pipe.open(); print(r2.cmd('pdj 1'))"
3. See the result in the terminal **from which cutter was opened**, it seems to be a mix between JSON and HTML. This makes the scripts previously working, failing.

**Expected behavior**
JSON output is expected.

**Additional Context**
This was working perfectly on 1.7.2 so I think it is related to a recent change.

**PS**
Thank you guys for your great job

**Comment by xarkes** [comment]
Hello,
As far as I can tell, this is because `e scr.html=true` is set so you can get colorized output from the console.
A temporary fix could be to detect if a command starts with `#!` and set `scr.html` to false.

**Comment by qjerome** [comment]
Hi,

Thanks, I did not know that env variable. I can simply disable the feature into my scripts using r2pipe.

I guess the issue can be closed since it is not really a bug ...
