### ISSUE TITLE
If the project is type GIT, saving will block GUI with GIT-COMMIT in console

### ISSUE THREAD

**Issue by smarek** [rizinorg/cutter#1091]
**Environment information**
* Operating System: Linux x64
* Cutter version: Latest release  Cutter-v1.7.3-x64.Linux.AppImage
* File format: irrelevant?

**Describe the bug**
Saving project of type GIT (prj.git=true) will block UI, with no visual hint of "git commit" running in background (or in parent terminal, if launched from terminal)

**To Reproduce**
1. Open GIT project / Create GIT project
2. CTRL+S to save
3. UI will not respond, if you've launched Cutter from terminal, you'll see commit editor of your user git settings
4. You have to either terminate the editor or switch to terminal, add commit message and save, to unblock Cutter

**Expected behavior**
Visual window with commit or visual notification of commit running in background.
Also simple dialog "enter commit message" with OK / CANCEL buttons would suffice, if the project save then ran in background

**Comment by XVilka** [comment]
@thestr4ng3r is this still a problem with the new projects?

**Comment by xarkes** [comment]
Also is it still relevant to have 'git' projects?

**Comment by thestr4ng3r** [comment]
No, git projects don't exist anymore. It's up to the user to use git themselves.
