### ISSUE TITLE
Cutter Icon resolution is bad

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#1281]
**Environment information** 
* Operating System: Any
* Cutter version: Master
* File format: Any

**Describe the bug**

As can be seen in the following screenshots, the Icon of Cutter doesn't look good. It is pixelated (first screenshot) and quite small in compared to others (second screenshot)

![image](https://user-images.githubusercontent.com/20182642/54132018-27dbcc80-441c-11e9-9ac5-60f32f75dd95.png)

![image](https://user-images.githubusercontent.com/20182642/54132061-37f3ac00-441c-11e9-9031-efa0e0948384.png)

**To Reproduce**

1. Try zoom in the Cutter icon on different machines. Mac and Linux shows it well

**Expected behavior**

Cutter's ICON should look smooth and pixel-free in any size.

**Screenshots**

Attached above

**Comment by thestr4ng3r** [comment]
ICON!!1!

**Comment by thestr4ng3r** [comment]
size is fine for a round logo on macOS, it's just ghidra trying to show off ;-) but it's pixelated indeed.
![Bildschirmfoto vom 2019-03-11 15-48-32](https://user-images.githubusercontent.com/1460997/54132816-2ce94d80-4415-11e9-9a24-51b7d08e9a4a.png)

**Comment by XVilka** [comment]
I think it was fixed by @thestr4ng3r already.

**Comment by XVilka** [comment]
@ITAYC0HEN @thestr4ng3r wasn't this fixed? I don't notice anything on my Mac

**Comment by thestr4ng3r** [comment]
Looks fine here at least. And the icon is a different now anyway on macOS so I guess this is outdated.
