### ISSUE TITLE
Improve basic blocks organization

### ISSUE THREAD

**Issue by xarkes** [rizinorg/cutter#1325]
**Current graph layout**
![image](https://user-images.githubusercontent.com/10772605/54513487-e08f9780-4957-11e9-9f09-2e59d877b34b.png)

**IDA graph layout**
![image](https://user-images.githubusercontent.com/10772605/54513492-e2f1f180-4957-11e9-9858-691e31c92e01.png)

As you can see IDA has no margin in the boxes, the arrows are aligned on the same line (true false jump lines) and the space between basic blocks is much smaller.

**Comment by karliss** [comment]
Can this be closed now? It was significantly improved during 2019-2020. There is always room for further improvements, but it's nowhere near as bad as it was before.
