### ISSUE TITLE
RFE: Include r2dec binary build in Cutter

### ISSUE THREAD

**Issue by radare** [rizinorg/cutter#1341]
Imho r2dec works pretty reliably to be included by default in Cutter, works better than pdc in a variety of situations, and i know there are plans to support binary packages in r2pm and such, but i think it hurts no one to include some default plugins taken from radare2-release output.

* [x] r2dec
* [ ] r2frida

... anything else?

**Comment by Maijin** [comment]
r2dec is already shipped with Cutter

**Comment by pelijah** [comment]
> 
> 
> r2dec is already shipped with Cutter release

Only with Windows version

**Comment by radare** [comment]
Should be also available on linux and mac builds!!

**Comment by xgdgsc** [comment]
Looking forward to this included in linux AppImage.

**Comment by xarkes** [comment]
As a matter of fact, version v1.11.1 provides both r2dec and Ghidra decompilers on Linux.

**Comment by xgdgsc** [comment]
Thanks. I used that. And I tried to build retdec woth cutter plugin, I copied the retdec plugin so to the path of plugins. But on selection of retdec in cutter decompiler it  crashes. Is there a prebuilt cutter with retdec available?

**Comment by xarkes** [comment]
No, there is no prebuilt Cutter with retdec.
I'm closing this issue as the latest releases ship both decompilers.
