### ISSUE TITLE
Breakpad doesn't build on macOS with XCode >= 10.1 by default

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/cutter#1440]
Original issue: https://bugs.chromium.org/p/google-breakpad/issues/detail?id=778&q=macos
Fix: https://chromium-review.googlesource.com/c/breakpad/breakpad/+/1338279
I have updated prepare_breakpad_macos.sh to use a fixed commit and apply the patch. This should be removed when the above fix is merged.

**Comment by XVilka** [comment]
I am closing this as Breakpad was removed
