### ISSUE TITLE
Support type xrefs

### ISSUE THREAD

**Issue by radare** [rizinorg/cutter#1577]
This is showing the xrefs to the addrss, but r2 is able to show the refs to a local var, as well as the refs to the int32_t type itself (where is this type used, etc), see the `tx` command.

<img width="568" alt="Screenshot 2019-05-21 at 14 08 03" src="https://user-images.githubusercontent.com/917142/58094838-dac16700-7bd1-11e9-93c2-4e102fb67073.png">

**Comment by xarkes** [comment]
I think we can close this issue, the feature is implemented as `Shift + X` for local variables.
AFAIK We don't provide a shortcut to get cross references to a specific type.
