### ISSUE TITLE
Mouse over tooltip useless highlights

### ISSUE THREAD

**Issue by radare** [rizinorg/cutter#1767]
<img width="516" alt="Screenshot 2019-09-09 at 06 38 33" src="https://user-images.githubusercontent.com/917142/64503703-8949fe80-d2cc-11e9-93f8-7ee25a7aa8d0.png">

imho cutter should filter out this

**Comment by a1ext** [comment]
Hi @radare do you mean to drop entire `Highlights` section?

**Comment by xarkes** [comment]
Ping @radare, could you precise your thoughts?

**Comment by xarkes** [comment]
Closing due to a lack of details.
