### ISSUE TITLE
Add support to export (documented) compiling assembly

### ISSUE THREAD

**Issue by oliv3r** [rizinorg/cutter#1866]
**Is your feature request related to a problem? Please describe.**
I have used cutter to annotated a binary dump to learn to understand what is happening. I would like to be able to export this dump so that I can push it in my git repository.

Additionally, the dumped assembly should be able to compile again.

The disassembly view already yields almost everything that is needed for this, so being able to export this view would be already extremely helpful.

I guess this is slightly related to https://github.com/radareorg/cutter/issues/1688

**Comment by ITAYC0HEN** [comment]
I am not sure that our disassembled output can be compiled due to the information the compiler and other components modified, added or removed. 
For the meantime, I suggest you dump the program using radare2 commands such as `pd <size> @ <address>`

**Comment by ITAYC0HEN** [comment]
Hey @oliv3r, from what I understand - the feature request is to export the entire disassembled program to a file so it will be able to be compiled using an assembler.
If so, I am afraid this is out of the scope of Cutter as we don't try to produce an output that can be compiled.

That said, requesting a feature in which you will have an output of the disassembly of the entire program in a file, is something else. If it is what you want, please feel free to open an issue on Rizin or Cutter, depends on your specific request.

Thank you for taking the time to open this issue :)
