### ISSUE TITLE
Ghidra decompiler not working after saving problem

### ISSUE THREAD

**Issue by lazytanuki** [rizinorg/cutter#1891]
**Environment information**
* Operating System: Arch Linux
* Cutter version: Cutter-v1.9.0-x64.Linux.AppImage
* Dependencies : I removed all radare2 packages from the system, to see how it goes with what's in the appimage

**Describe the bug**

When saving a project and re-opening it, the ghidra decompiler parser no longer works ("Failed to parse JSON from r2ghidra")

**To Reproduce**

Use the app image, save a project, reopen it, and try to use the decompiler.

**What I think the problem is**

I think I have found a cause for this problem, as well as a functioning workaround until a fixe is made. When saving the project, the rc file has the following line :

`"e r2ghidra.sleighhome = /tmp/.mount_CutteryMD9MD/usr/share/radare2/plugins/r2ghidra_sleigh"`

Given that the plugins seem to be temporarily mounted, when restarting cutter the path may have changed, giving my error.

**Workaround**

I simply remove that line from the rc project file (`sed -i '/ghidra.*home/d' rc` is enough)

**Side note**

I'd like to thank everyone who has been working on this marvelous project, which is now even better now with the implementation of ghidra's algorithms. Many hugs to y'all ! :)

**Comment by ITAYC0HEN** [comment]
Sorry for getting to the issue only now, thank youfor your nice words! Appreciate it :)

CC @thestr4ng3r

**Comment by meowmeowxw** [comment]
I have the same problem on arch linux, but instead of "Failed to parse JSON from r2ghidra" I get "// Ghidra Decompiler Error: No sleigh specification for x86:LE:64:default".

The solution is the same as the one found by @lazytanuki:

`sed -i '/ghidra.*home/d' rc`

I tried from cutter version 1.10.1 to 1.10.3 and they have all this problem

**Comment by xarkes** [comment]
Does anyone know if this issue is still relevant as of `2.0.2`?

**Comment by XVilka** [comment]
Closing this as a lot has changed since and no further information was given
