### ISSUE TITLE
Mac OS Crash in Cutter

### ISSUE THREAD

**Issue by Maijin** [rizinorg/cutter#1957]
**Environment information**
* Operating System: Mac OS
* Cutter version: 1.10
* File format: PE

**Describe the bug**

Cutter crashed see crashdump

**To Reproduce**

User opened the PE and it eventually crashed.

**Expected behavior**

Cutter doesn't crash

[Cutter_crash_dump_21.12.19_10.32.37.dmp.zip](https://github.com/radareorg/cutter/files/3991276/Cutter_crash_dump_21.12.19_10.32.37.dmp.zip)

From @Th4nat0s

**Comment by XVilka** [comment]
Need to check first if this still happens.

**Comment by Th4nat0s** [comment]
Can't reproduce, run with Version 2.0.3

**Comment by xarkes** [comment]
Thanks for the feedback, marking as solved :)
