### ISSUE TITLE
Failing to open saved project

### ISSUE THREAD

**Issue by AxelPotato** [rizinorg/cutter#1971]
**Environment information**
* Operating System: Ubuntu 19.04 VM
* Cutter version: 1.10 AppImage
* Obtained from: 
  - [x] Downloaded from release
* File format: ELF64

**Describe the bug**

I am working on a 10 Mb binary file.
When I save the project the newly created rc file is ~36Mb
When attempting to open the project again cutter freezes and attempt to force quit due to unresponsiveness.

**To Reproduce**

1. Open a 10Mb ELF64 file
2. Save the project.
3. Attempt to open the saved project.
4. cutter freezes

**Expected behavior**

Cutter is expected to open the project/

**Additional context**

I really like cutter ^^ I find it amazing. I really hope this functionality will work properly.

**Comment by karliss** [comment]
It is know that current project implementation is quite problematic. New project saving mechanism is currently being written from zero.

**Comment by AxelPotato** [comment]
Gotcha thank you.

**Comment by ITAYC0HEN** [comment]
@AxelPotato I want to thank you for the time you take to open issues and report to us the problems you experience. This is highly important for us! 😊
Your rock!

**Comment by ITAYC0HEN** [comment]
Hey Axel! :) 
Good news! Cutter now uses the new Projects that were introduced in Rizin. The experience should be much better.

I will close this issue for now. Please open a new issue if you experience issues with the new projects.

(the Projects are not yet available in a release as we didn't release a new version. Only when building from source)
