### ISSUE TITLE
Organize notes, roadmaps, projects and milestones in a better way

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#2115]
**Is your feature request related to a problem? Please describe.**

We currently focus on using GitHub to manage Cutter. This includes issues, pull requests and partially milestones and projects. While this is nice, we still have a lot of details and important docs we write in the process that we don't manage in one place.

Example to such documents are:

1. Meeting Notes
2. [Hexdump specifications](https://hackmd.io/6To_DPB6QXC1MEFIYuNUIg)
3. [Debugger UI, UX and specifications](https://hackmd.io/__K1e8IaRpSrcrYWTF5gNQ)
4. [Cutter menu Options](https://hackmd.io/4MTXK8GnRiOba36mUHVVfA)
5. [Python plugins and High Level API](https://hackmd.io/83H4-B3QSy-3gwxftlPLRQ)

In addition to this, we are failing to create a flow of roadmap and contributors that are assigned to a long-task project with clear goals and timelines. This will help us better organize ourselves and the team of developers.

**Describe the solution you'd like**

While I truly love Github, it is not enough to manage such stuff. A 3rd party application coule help here. I personally fond of [Notion](https://www.notion.so/product). Visit the web page, give it a try, see the templates, etc.

![gif](https://www.notion.so/front/product/use-case-screenshot-wiki.gif)

**Comment by XVilka** [comment]
I am closing this as completed (partially). Feel free to open a new issue if something particular is missing.
