### ISSUE TITLE
Stack is always empty while debugging an elf file

### ISSUE THREAD

**Issue by int3rsys** [rizinorg/cutter#2121]
**Environment information**
* Operating System: Ubuntu 18.04.1 64bit
* Cutter version: 1.10.1
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded from release
  - [ ] Distribution repository
* File format:

When I start a debugging session, after hitting my breakpoint (doesn't matter where in the program), the stack is always filled with zeroes. It does grow, but the values are not inserted. Just zeroes.

**To Reproduce**

1. Open x5 binary
2. Put a breakpoint somewhere
3. Observer that the stack is zeroed
4. Step through a push instruction 
5. See that a zero is being pushed 

**Expected behavior**
Well, real values being pushed.

**Screenshots**
![Screenshot from 2020-03-31 12-48-10](https://user-images.githubusercontent.com/22496238/78069112-3cca2b80-73a2-11ea-860d-c08ce385b50a.png)
You can clearly see that the stack filled with zeroes, even after pushing 3 values.
**Additional context**

[x5.zip](https://github.com/radareorg/cutter/files/4411273/x5.zip)

**Comment by ITAYC0HEN** [comment]
Confirmed on the latest version from git (v1.10.3-pre). I wonder if it is caused by radare2.
The problem does not exist in other platforms (gdb, IDA, ...)

**Comment by ITAYC0HEN** [comment]
@yossizap can you have a look on this?

**Comment by abcSup** [comment]
Here is what I found:

`CutterCore::getAddrRefs` only set the `value` if the address has read, but not exec permission.
https://github.com/radareorg/cutter/blob/master/src/core/Cutter.cpp#L1411
```
if ((type & R_ANAL_ADDR_TYPE_READ) && !(type & R_ANAL_ADDR_TYPE_EXEC)) {
...
  json["value"] = QString::number(n);
...
}
```
In this case, the `[stack]` memory map has `rwx` permissions so the value of each stack address is not assigned.

**Comment by FerriteGiant** [comment]
Still an issue in v1.12.0

If the reason is the permissions of the memory map, Is there a workaround involving changing permissions somewhere?
