### ISSUE TITLE
Register flags act weird in Cutter

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2155]
**Environment information**
* Operating System: ArchLinux
* Cutter version: <1.10.3,  8957e5eb64eccae1ee4dfa55cab0f217c7d0c667
* Obtained from: Built from source
* File format: ELF x86_64

**Describe the bug**

Debug flags don't seem to be working correctly in Cutter seem to be working in r2. Values don't match registers and the flagspace are wrong.

* Some of the register flags are in class flagspace
* Register flag values don't match registers
*  When starting debuging functions move from function flagspace to classes

Opening a file in r2 and then doing `ood` and steps bellow doesn't seem to have the same problem, but it still causes function flags to be moved from functions to classes.

**To Reproduce**

1. Open executable
2. `fs` to check flag count in each flagspace
3. start debuging, break at main
4. `fs` to check flag count -> observe flag count weirdness
5. list flags in classes namespace -> observe that r9 flag is in classes namespace and has wrong value

**Expected behavior**

* When debuging register flags are in register flagspace
* Register flag values are correct
* After finishing debuging register flags are removed

**Screenshots**

```
[0x5625801370ac]> fs regs
[0x5625801370a2]> f
0x7f12df772100 8 rip
0x7fffb63eb2f0 8 rsp 
[0x5625801370ac]> dr~rip
rip = 0x5625801370a2 

[0x5625801370ac]> fs classes
[0x5625801370ac]> f~r12
0x562580133000 8 r12 
[0x5625801370ac]> dr~r12
r12 = 0x562580138b20 
```
**Additional context**

**Comment by karliss** [comment]
Additionally once this is fixed register wigets will probably have slightly wrong positions due to #2142 , but this issue about them being wrong even in console widget.

**Comment by XVilka** [comment]
Not reproducible anymore.
