### ISSUE TITLE
CmdRawAt is slow due to seek causing io read

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2156]
**Is your feature request related to a problem? Please describe.**

CmdRawAt calls `r_core_seek(core, offset, rb=true)` twice for the temporary seek and return. r2 implements `@` modifier in similar way.  `rb=true` causes 4k read from IO to `core->block`. If CmdRawAt gets called multiple times by a widget this can quickly accumulate performance penalty especially during debugging when io reads are slower. See #2154 as example. This is less obvious in r2 where most commands are called manually compared to Cutter which automatically refreshes a bunch information.

**Describe the solution you'd like**

* Prefer use of commands that accept position as argument (either as r2 commands or c functions) instead of global seek position.
  * reduces the performance issue
  * Removes the dependency on global state. The global seek should be more of interface property and maybe internal implementation detail of some IO plugins. For better API the functions implementing main logic of commands shouldn't know anything about interface feature like global seek.
* Improve the r2 API in situations where use of global offset is only way of specifying command target
* Get a better understanding of how core->block is used in r2, discuss moving the block read from seek to the commands using io memory with rest of r2 developers.

Keep this issue in Cutter as the problems described affect Cutter more than r2 itself. Once it's clear what changes would help Cutter, more specific issues or PR can be created in r2 repo.

**Comment by XVilka** [comment]
With the migration to using the API directly it's now irrelevant.
