### ISSUE TITLE
Indicate that search is in progress

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#2161]
**Describe the solution you'd like**
When searching in huge files, there's is no clear indication that Cutter is searching (except freeze).

In addition, when search finishes very fast (say, in tiny binary) and no results found, then there is no indication for this, and it feels like clicking the button does nothing

![search_no_response](https://user-images.githubusercontent.com/20182642/79644307-cbb3b200-81b0-11ea-8e31-5eb66e8329d5.gif)

- [ ] Add indication to the Search widget that a search is currently in progress
- [x] Add an indication that no results were found

**Comment by Surendrajat** [comment]
@ITAYC0HEN I tried to do it this way:
Append a `Data` item in `SearchDescription` saying "Searching" or "No result found!".
While the later worked fine, the first one doesn't as I added it before `beginResetModel()`. Any suggestions?

**Comment by karliss** [comment]
How about disabling the Search button while it's in progress?

**Comment by karliss** [comment]
I don't this issue can be properly implemented before the big async refactoring. @ITAYC0HEN might have rushed it with marking this as good first issue.

**Comment by ITAYC0HEN** [comment]
I will clarify what I am thinking ->

1. User clicks the <kbd>Search</kbd> button
2. Change button's text to "Searching..."
3. Disable button
4. If needed, force `redraw` of the button
5. Perform search
6. If results found, shown on the table. If results were not found, show the "No results found" indicator
7. Return the button's text to "Search"
8. Enable the button

**Comment by rakeenz** [comment]
Has this issue been resolved yet? How big of a file triggers this issue? I am unable to replicate it.

**Comment by xarkes** [comment]
As far as I know there is no visual information stating the search has started.
About the file size I don't know but I'm pretty sure any file >50MB would do it.
