### ISSUE TITLE
Useless LGTM configuration

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2254]
**Describe the bug**
It seems that LGTM currently only checks python code. There are now C++ problems reported. In some views it reports only ~2k lines of code.  Files view shows only header files.  But the Logs page claims that 684.6k lines of C and C++ code were analyzed. Looking at extraction log it seems that the build fails after compiling r2 which is probably excluded.

**Comment by XVilka** [comment]
It is possible to use CodeQL directly from GitHub now, without the LGTM:
- https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-alerts-from-code-scanning

**Comment by XVilka** [comment]
I am closing this since we already have Coverity for Cutter
