### ISSUE TITLE
Document how to build Cutter on macOS using CMake

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#2310]
**Is your feature request related to a problem? Please describe.**

We don't have explanation for how to build Cutter on macOS using CMake. While it is very similar to building Cutter on Linux, it still has some differences.

**Describe the solution you'd like**

Add a section for building Cutter using CMake on macOS. Make sure to instruct how to install most of the things using homebrew and make sure to explain how to build Shiboken properly.

The documentation should be added to the "building" page at https://cutter.re/docs/building.html

**Comment by Surendrajat** [comment]
This has been already done hence closing.
