### ISSUE TITLE
Hide useless help button

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2342]
**Is your feature request related to a problem? Please describe.**

Currently Cutter doesn't use annotations for [what's this mode](https://doc.qt.io/archives/qt-4.8/qwhatsthis.html) so there is no point having help button in tittlebar.
![question](https://user-images.githubusercontent.com/7101031/88784363-a0216a00-d198-11ea-8b33-dc4ac5c91543.PNG)

**Describe the solution you'd like**

* It should be possible to deal with most cases using Qt::AA_DisableWindowContextHelpButton attribute.
* If solution above doesn't apply to everything set the corresponding dialog attribute
* Remove manual clearing of WindowContextHelpButtonHint flag in cases it became unnecessary due to AA_DisableWindowContextHelpButton . 

**Describe alternatives you've considered**

**Additional context**

**Comment by shane424** [comment]
Has this been resolved? If not I'd like to take it.

**Comment by ITAYC0HEN** [comment]
Hi @shane424 :) 
It was not resolve. Please feel free to work on it and ask any question that might raise during the way. We would love to assist wherever needed :)

**Comment by ITAYC0HEN** [comment]
@shane424 
what you need to do is to disable the help button globally.

You can use global attributes, like this:

```cpp
QApplication::setAttribute(Qt::AA_DisableWindowContextHelpButton);
```
