### ISSUE TITLE
Flags are not saved in project

### ISSUE THREAD

**Issue by lephe** [rizinorg/cutter#2350]
**Environment information**
* Operating System: arch 
* Cutter version: 1.10.3
* Obtained from: Distribution repository
* File format: pe
 * Arch: x86
 * Type: DLL (Dynamic Link Library)

**Describe the bug**
Flags added through the "Add Flag" context menu (for instance in the disassembly window) are not saved with the project file and disappear when the project is reloaded.

**To Reproduce**
1. Open a file in a new project
2. Add a flag anywhere
3. Save as a new project and quit
4. Reload project
5. Flag is not shown in project
6. Check the `rc` file for the flag
7. Flag does not appear in `rc` file

**Expected behavior**
Flags are expected to be saved with the project, as with r2's command-line `Ps` command.

```
% r2 /bin/ls
 -- There is no F5 key in radare2 yet
[0x00005b20]> f test_flag
[0x00005b20]> Ps test_project
test_project
[0x00005b20]> q
Do you want to save the 'test_project' project? (Y/n) Y
% r2 /bin/ls
 -- Quantum dissasemble: it's there as long as you don't observe it
[0x00005b20]> Po test_project
Close current session? (Y/n) Y
No file to load bin from?
[0x00005b20]> fs *
[0x00005b20]> f~test_flag
0x00005b20 1 test_flag
[0x00005b20]> q
Do you want to save the 'test_project' project? (Y/n) Y
% grep test_flag ~/.local/share/radare2/projects/test_project/rc
f test_flag 1 0x00005b20
```

**Comment by lephe** [comment]
After digging deeper it seems that the determining factor is at project creation time rather than at project save time, since :

* A project created by Cutter after opening from `file://` presents the problem and cannot have flags added or saved by command-line `r2`
* A project created by command-line `r2` does not present the problem and can have flags added and saved by Cutter

The main difference being that Cutter creates a `prj.simple` project by default while r2 does not. And sure enough, r2 doesn't save flags with a simple project either, and Cutter does save flags (temporarily) when disabling `prj.simple` in the project save dialog. (Except that it is enabled again when hitting "Save" when closing Cutter!)

From [`libr/coree/cconfig.c`](https://github.com/radareorg/radare2/blob/master/libr/core/cconfig.c#L3191), it seems that `prj.simple` is meant to save only functions, comments, and options, and it's disabled by default in r2.

So I guess the problem is now identified and the main questions are :
* Why does Cutter enables and recommends `prj.simple` by default if there is a risk of data loss for users coming from r2?
* Why does Cutter enable simple style in the closing dialog even when the projects were saved in the normal style before?

**Comment by lephe** [comment]
Just to clarify, every "flag" mentioned in this issue is a non-local flag. [`simple_project_save_script()`](https://github.com/radareorg/radare2/blob/master/libr/core/project.c#L568) accepts the `R_CORE_PRJ_FLAGS` category but only saves local flags through `f.**`; [`project_save_script()`](https://github.com/radareorg/radare2/blob/master/libr/core/project.c#L641) seems to be more thorough.

Apparently Cutter sets `prj.simple` to false only through the Save As dialog and ends up going back to the simple style as soon as C-s or the Save button of the exit dialog is hit. This may be why disabling `prj.simple` still resulted in flags being eaten in https://github.com/radareorg/cutter/issues/263#issuecomment-653432921. Without delving too deep into the code, I believe that [saving the project settings in a temporary config](https://github.com/radareorg/cutter/blob/master/src/dialogs/SaveProjectDialog.cpp#L70) is a clear hint at why this is happening.

May I ask whether it would be welcome to make these settings permanent in a way similar to using the `e` command in the console?

As one would expect, `e prj.simple = false` in the console ensures that simple mode is not used during C-s and closing Cutter. However because of the new IO maps [it causes `file.path` and `file.lastpath` to be cleared by r2](https://github.com/radareorg/radare2/blob/master/libr/core/project.c#L666) which confuses Cutter into either not loading anything, or freezing during the load on both the distribution version and the current `master`. Which I believe links with https://github.com/radareorg/cutter/issues/2275.

**Comment by ITAYC0HEN** [comment]
Hey @lephe. Since this issue was opened, we added support for the newly created Projects in Rizin. So Cutter should now support flags properly.

I will close this issue for now, but please test it once again and make sure that indeed it is resolved.
Thank you!
