### ISSUE TITLE
Add labels to analysis slider

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2355]
**Is your feature request related to a problem? Please describe.**

It is not obvious that Advanced/Custom analysis mode is on the right side of slider.

**Describe the solution you'd like**

![anlysis](https://user-images.githubusercontent.com/7101031/89031336-fa5a3080-d33a-11ea-957f-d7caae29ee11.png)
I don't think the builtin Qt slider has support for attaching labels directly, but the amount of them is small so spacing them out evenly should be good enough.

In my opinion "Custom" is better name than "Advanced" for the last option.

If there are very strong objections against aaa and aaaa, labels can also be 0 1 2 custom.

**Describe alternatives you've considered**

I understand that there are various ideas for much bigger changes to analysis UI, but this is something that is very easy to do right now until we figure out a better solution.

**Additional context**

**Comment by ITAYC0HEN** [comment]
-ף
would have these levels in the slider:

None -> Automatic -> Custom 

for automatic I'd go for "aaa" unless you believe that "aaaa" is better (but not both)

**Comment by karliss** [comment]
Why not both? Can be called None, Automatic, Experimental, Custom

**Comment by ITAYC0HEN** [comment]
Because it doesn't give any information to the user. I'd choose Automatic or Experimental arbitrary without having idea what am I doing and why will I gain or risk with the "Experimental". I want to guarantee the best experience to the users and not having a guessing-game.

**Comment by 7h3qu1rkyb1t** [comment]
why not None->auto->deep(may take quite some time)->advanced
