### ISSUE TITLE
Missing `getBIHighlighter` binding

### ISSUE THREAD

**Issue by Emi1305** [rizinorg/cutter#2395]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 1.11.0 (`cmake -B build -DCUTTER_USE_BUNDLED_RADARE2=OFF -DCUTTER_ENABLE_PYTHON=ON -DCUTTER_ENABLE_PYTHON_BINDINGS=ON -DCUTTER_ENABLE_GRAPHVIZ=ON -S src; cmake --build`)
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: N/A

**Describe the bug**
When writing a python plugin for Cutter, attempting to call `CutterCore.getBIHighlighter` result in the following exception:

    Exception in partial paint: 'CutterBindings.CutterCore' object has no attribute 'getBIHighlighter'

**Expected behavior**

The method `getBIHighlighter` should return an instance of a `BasicInstructionHighlighter`

**Additional context**

Looking at the file `build/bindings/CutterBindings/cuttercore_wrapper.cpp` it can be observed that the binding for the `getBIHighlighter` method is not created. During compilation no error is shown regarding this method

**Comment by XVilka** [comment]
@Emi1305 does this still happen? Could you please retry with the latest version? A lot has changed since.

**Comment by XVilka** [comment]
I tried this myself, and confirm - it's still not available. For example, `getBBHighlighter` is available, but not `getBIHighlighter`
