### ISSUE TITLE
Comment edit bug

### ISSUE THREAD

**Issue by ghost** [rizinorg/cutter#2423]
**Environment information**
* Operating System: Windows x86_64
* Cutter version: 1.12.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: NA

**Describe the bug**

Changing the comment isn't possible if "\x00" is present. It works if I append or delete the existing comment.

**To Reproduce**

1. Go to any instruction (in disassembly or graph view)
2. Press the ";" key
3. Enter something followed by "\x00"
4. Click on "Ok" button
5. Now deleting existing chars from the comment won't work
6. Deleting the entire comment or appending to the comment works

**Expected behavior**

Comments should always be editable whenever required

**Screenshots**

![cutter-comment-bug](https://user-images.githubusercontent.com/17880848/92302828-d4086000-ef8c-11ea-9752-a92caea17a30.gif)

__EDIT__ Fixed "Obtained from" info

**Comment by karliss** [comment]
Windows doesn't have distributions. Microsoft has quite a few package managers but as far as I am aware none of their repositories contain Cutter. So where did you get it exactly?

Doesn't seem to be related to '\x00' string. Any change to comment where new comment is substring in old comment is ignored. Need to discuss with r2 devs why such behavior is implemented.

**Comment by gmastergreatee** [comment]
Sorry I downloaded radare2 from local repository listing, and confused it with cutter download source.

**Comment by XVilka** [comment]
This one isn't reproducible anymore. Fixed.
