### ISSUE TITLE
macOS builds are broken

### ISSUE THREAD

**Issue by vit9696** [rizinorg/cutter#2428]
**Environment information**
* Operating System: macOS 10.15.6
* Cutter version: 1.12.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Crashes on startup:

```
Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_FRAMEWORK_PATH=/Applications/Cutter.app/Contents/MacOS/../Frameworks
DYLD_LIBRARY_PATH=/Applications/Cutter.app/Contents/MacOS/../Frameworks

Dyld Error Message:
  Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Applications/Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python
  Reason: image not found
```

**To Reproduce**

Open Cutter.

**Expected behavior**

Continue to use IDA Pro :)

**Screenshots**

![image](https://user-images.githubusercontent.com/4348897/92945597-2dc1cc00-f45e-11ea-8dbb-8425c07c04e5.png)

**Comment by ITAYC0HEN** [comment]
Thanks for reporting this issue :)
The release works on my macos machine, we will investigate what went wrong when running on yours.
Thank you again!

**Comment by karliss** [comment]
@ITAYC0HEN From the error log it seems that it is trying to load a dynamic library outside the app. I assume that the macOS machine on which you tried it happened to have the same library installed in the same place. Depending on OS libraries might be fine in some cases, but `/usr/local/opt` is probably from homebrew. The .app should be selfcontained and not depend on homebrew libraries being installed to run.

**Comment by doublegrey** [comment]
Please check installation source. It seems like you have installed Cutter via Homebrew instead of using precompiled release package. However, if you want to use current version please consider following [this](https://stackoverflow.com/a/15983461) dirty hack.
Have a nice day!

**Comment by vit9696** [comment]
Downloaded from here: https://github.com/radareorg/cutter/releases/tag/v1.12.0

**Comment by doublegrey** [comment]
I tried to reproduce your issue on my macOS Catalina Version 10.15.6 and macOS Mojave 10.14.6
It seems like described error is related to your system, the release build is fine. As a workaround, please try [building from source](https://cutter.re/docs/building.html)
Have a nice day!

**Comment by vit9696** [comment]
The release build contains references to Homebrew `libintl.8.dylib`, which is obviously not supposed to be present on a vanilla system:

```
$ otool -L Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python
Cutter.app/Contents/Frameworks/Python.framework/Versions/3.6/Python:
	/Users/travis/build/radareorg/cutter-deps/python/Python.framework/Versions/3.6/Python (compatibility version 3.6.0, current version 3.6.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1454.90.0)
	/usr/local/opt/gettext/lib/libintl.8.dylib (compatibility version 11.0.0, current version 11.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

The library is not bundled with the app either (no output other than that):

```
$ find Cutter.app -name libintl.8.dylib
```

This makes it obvious that your assumption about my system being the cause of a problem is not valid, but rather your binaries contain dependencies they are not supposed to have.

Check `man install_name_tool` to understand how you can resolve such issues when bundling the applications. I once dealt with a similar problem when bundling the software built with MacPorts and attached a script I wrote for that purpose. Perhaps it can be used as a reference. [deployfix.sh.zip](https://github.com/radareorg/cutter/files/5232007/deployfix.sh.zip)

**Comment by karliss** [comment]
We are currently using windeployqt, linuxdeployqt and macdeployqt for this purpose. As you observed in configuration it misses some libraries. Cutter is currently lacking macOS developers so @vit9696 if you feel comfortable with this topic pull request would be appreciated. The top level script currently doing packaging can be found here https://github.com/radareorg/cutter/blob/ad66718f375b013a3021e531891c71082ee48867/.travis.yml#L233 .

Don't know about macdeployqt but at least the corresponding Linux tool can copy all the libraries not only Qt and it's direct dependencies. Might be worth checking if changing the the orde so that macdeployqt gets run after packaging python helps in any way. If not then the python packaging script needs to be modified.

**Comment by SteveMoore18** [comment]
MacOS Building error. 

![Снимок экрана 2020-09-25 в 14 53 46](https://user-images.githubusercontent.com/45648018/94264219-f7e11500-ff3e-11ea-90aa-77d2af6d0f07.png)

**Comment by karliss** [comment]
@SteveMoore18 Please do not post unrelatated problems to existing issues. Also your issue is most likely due to use of incompatible r2 version. Please use the version specified in submodule which is also what CI build use, anything else is not guaranteed to work.

**Comment by cheemeng** [comment]
MacPorts user here. I have gettext installed and my libraries are installed in /opt/local/lib instead, so by re-creating the directory as expected and doing a softlink, I can get Cutter to run for now. A temporary workaround I know, but at least it runs :-) 

`
sudo mkdir -p /usr/local/opt/gettext/lib
sudo ln -s /opt/local/lib/libintl.8.dylib /usr/local/opt/gettext/lib/libintl.8.dylib
`

**Comment by NikitaMalakhov** [comment]
Just install ```
brew install gettext
```. I added this problem to troubleshooting section in building from source doc.

**Comment by ITAYC0HEN** [comment]
We added a potential solution for it to our docs in PR #2436 Please check if it fixes your issue :)

**Comment by vit9696** [comment]
It is not a "potential solution", because I obviously _can_ workaround the problem myself. Point is, neither I, nor many other people use brew, and I third-party libraries should not be a requirement to launch the application. Fix your build scripts please.

**Comment by karliss** [comment]
"potential solution" might have been bad choice of words. Yes, fixing build scripts is the proper solution. Until that happens knowing a workaround is useful for some people assuming they need to get Cutter working at any cost.

**Comment by ICEBERG98** [comment]
Since Brew would not be a native solution, would making gettext from GNU Ftp tar archive work? Could this be a potential resolution to this issue? 
If yes, I would be happy to help.
cc: @ITAYC0HEN / @karliss / @NikitaMalakhov

**Comment by karliss** [comment]
@ICEBERG98 I have a feeling that you misunderstood the problem. gettext from GNU Ftp archive wouldn't be any better or worse than one from brew. Where it's obtained from is partially orthogonal to the problem of Cutter packaging scripts not including all the transitive dependencies. How it's obtained mostly depend on how the direct dependencies of Cutter compiled and linked.

**Comment by rattatosk** [comment]
> Just install
> `brew install gettext`
> I added this problem to troubleshooting section in building from source doc.

This fixed it for me ! Thanks !

**Comment by Kxrr** [comment]
install `gettext` does not works for me, while using the older version of [cutter](https://github.com/rizinorg/cutter/releases/tag/v1.11.1) works.
