### ISSUE TITLE
Cannot open file in write mode

### ISSUE THREAD

**Issue by Radion94200** [rizinorg/cutter#2437]
**Environment information**
* Operating System: Parrot OS
* Cutter version: Cutter-v1.12.0-x64
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: .bin

**Describe the bug**

Cannot open files in write mode.

**To Reproduce**

1. Set full rights on program(chmod 777)
2. Launch Cutter
3. Select the previous file
4. See errors: The error message differs - **select a new program or a previous one before continuing** - or - **Could not open the file! Make sure the file exists and that you have the corrects permissions** - 

**Expected behavior**

Open the file in write mode to modify it 

**Screenshots**

**Additional context**

The previous test has been done with lots of binary files and always the same result.  
Cutter has been reinstalled too.

**Comment by ITAYC0HEN** [comment]
Hey @Radion94200, Would you mind joining into our chat groups (Telegram, IRC) in order to troubleshoot this issue easier?

I have some questions like - 
- how do you launch Cutter?
- did you try to open in from the commands line `Cutter -w -A 1 filename.bin`
- can you share screenshots of the right of the files?

etc

**Comment by Radion94200** [comment]
@ITAYC0HEN yes I can join them :)

I launch cutter with this command: `./Cutter-v1.12.0-x64.Linux.AppImage`
No i try to open it in the graphical interface and tick the option.

Like i said before rights are 777: `-rwxrwxrwx 1 plop plop 732 Sep 22 19:27 ch20.bin`

**Comment by Radion94200** [comment]
I try to open it with the command line you give to me.
And i have exactly the same error.

And i try this command: `strace ./Cutter-v1.12.0-x64.Linux.AppImage ch20.bin` and it works perfectly.
But don't know why.

**Comment by xarkes** [comment]
Hello, have you somehow managed to solve your problem?

**Comment by xarkes** [comment]
Due to a lack of response, I am closing this issue.
Feel free to reopen if needed.
