### ISSUE TITLE
Shortcut for 'Add Flag'

### ISSUE THREAD

**Issue by cw2k** [rizinorg/cutter#2478]
Rename functions and variables is really important stuff.

While we can press 'N' to rename a function there is 
**No shortcut for 'Add Flag'**.
Each time we have to right click 'Add Flag' to add some label.

Okay that brings me to next issue. Why is it call 'add flag'?
To to name Label is more suitable for that kind of 'symbol'.

## proposed changes:
1. Rename 'Add Flag' to 'Add Label'
2. Add a short ':' to invoke 'Add Label'
   (since the is already ';' for Add Comment')

## Some more stuff

3. Why can I add more than one flag to certain location?
Is it a bug or intended? 
Since for comments it is also just add comment to one location

4. Consider to make that 3 menu items [add, edit, remove] flag into just one with the name 'label'. 
It add a label -> if it is not there
It edit a label -> if there is already a label
It removes a label -> if you edit the label but delete all its text.

5. I need to 'visit' the location to add a label. 
Example: Disassembly is that line:
`0x14002b017      mov     dword [0x14013c068 ], 1`
To add a label on 0x14013c068 I can't do directly in disassembly.
I need to visit 0x14013c068 and invoke 'Add Label' and go back.
Would be cool to do that direct via 
'Add Label to ref '0x14013c068' or even better by a drilled up 
'Add label dialog' that allows to choose what to label. By showing up to 3 textfields depending on the currently location:
```
[Add Label - Dialog]

Base:             [_______________]
Referenance op1:  [_______________]
Referenance op2:  [_______________]
```

**Comment by xarkes** [comment]
Hello, thanks for opening the issue. There is an on-going work in order to improve the current workflow of renaming in general, which includes adding labels as well, see https://github.com/radareorg/cutter/pull/2468.

The term `flag` comes from radare2 code base, but you are completely correct, the term `label` is well more suitable.

3. This comes from radare2 land, I am not sure of the usefulness of it.
4. I agree with this workflow, but no decision was taken yet.

**Comment by cw2k** [comment]
Wow what a synchronicity. We got same idea at the same time and impulse to do something about.
Well nice to see that there is already a PR going on.

So I wait until thing got settle down in a release.
And be happy to close that issue.

Since it'll be no issue anymore.

**Comment by xarkes** [comment]
Note that current work will only improve the renaming workflow, it won't rename all occurrences of "Flag" into "Label". It might make sense to change this issue in this way.

**Comment by xarkes** [comment]
Hey, the PR has been merged for a while, I don't know if you had a chance to pull a dev version of Cutter and try it out, but I think this issue is fixed now.

**Comment by ITAYC0HEN** [comment]
Hey! I closed this issue in the meantime. Please let us know if we missed anything and it is still relevant and we can re-open it :)
