### ISSUE TITLE
cutter no longer compiles on ubuntu linux

### ISSUE THREAD

**Issue by dhucul** [rizinorg/cutter#2506]
Make Error at CMakeLists.txt:1 (include):
  include could not find load file:

    QMakeConfigureFile

CMake Error at CMakeLists.txt:2 (qmake_configure_file):
  Unknown CMake command "qmake_configure_file".

This error is recent. Always compiled before.

**Comment by Surendrajat** [comment]
@dhucul this is due to outdated build docs. We will soon try to deploy updated docs.

CC @ITAYC0HEN

**Comment by ITAYC0HEN** [comment]
Thank you for reporting this issue to us. Indeed we are working on document everything and putting it in-place, sorry fo the inconvenience. 

Following @Surendrajat instructions should do the trick for you. Please let us know if it solved the issue you are experiencing. If so, please mark this issue as closed.

Once again, we are sorry for the inconvenience :pray:

**Comment by dhucul** [comment]
Thanks for the update. It Worked!
