### ISSUE TITLE
Ghidra Decompiler Error: No sleigh specification for x86:LE:64:default

### ISSUE THREAD

**Issue by fr0ster** [rizinorg/cutter#2507]
**Environment information**
* Operating System: Debian GNU/Linux 10 (buster)
* Cutter version: Version 1.12.0
* Obtained from:
  - [] Built from source
  - [X ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: AppImage

**Describe the bug**

When open saved project on ghidra page appear message
Ghidra Decompiler Error: No sleigh specification for x86:LE:64:default

In rc file is string "e r2ghidra.sleighhome = /tmp/.mount_Cutterwzk4rk/usr/share/radare2/plugins/r2ghidra_sleigh"
If it remove project open without problem but after save project its string appear again

**To Reproduce**

1. Open binary
2. Save project with default parameters
3. Reopen Cutter and open project

**Expected behavior**

Project doesn't save in rc file uncorrect configs "e r2ghidra.sleighhome = /tmp/.mount_Cutterwzk4rk/usr/share/radare2/plugins/r2ghidra_sleigh"

**Comment by antidot3** [comment]
I'm getting the same error except i installed from AUR instead of building from source and I'm using Arch Linux

**Comment by Surendrajat** [comment]
This has been fixed in #2645. However, Cutter 2.0 will have a completely new project feature, so you may need to port your project over manually.
