### ISSUE TITLE
Switch from astyle to clang-format

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2508]
There was a lot of modified lines due to API changes this would be a good moment to finally switch.

**Comment by karliss** [comment]
I think I saw Qt having their clang format config published that might be a good starting point.

**Comment by xarkes** [comment]
Yes I agree I think it's a good time to make the switch.
Maybe are you referring to QtCreator's clang format? https://github.com/qt-creator/qt-creator/blob/master/.clang-format

**Comment by karliss** [comment]
I was probably thinking of this https://code.qt.io/cgit/qt/qt5.git/tree/_clang-format which is linked at the top of https://wiki.qt.io/Qt_Coding_Style
