### ISSUE TITLE
Switch Ubuntu 18.04 from cutter-deps to system deps

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2509]
Building cutter using cutter-deps on Ubuntu 18.04 adds very little value. Having a known working configuration and issues for building Cutter on Ubuntu 18.04 or 20.04 with as much features enabled as possibile would provide useful information.

**Comment by XVilka** [comment]
I also suggest to drop support for Ubuntu 16.04 since it reached EOL: https://endoflife.software/operating-systems/linux/ubuntu

It also stands in a way of updating C++ standard/Qt versions AFAIK.

**Comment by thestr4ng3r** [comment]
18.04 has Qt 5.15.2 with shiboken+pyside packaged, so this might work.

**Comment by XVilka** [comment]
It's strange why GitHub decided to deprecate 18.04 while it's LTS and didn't reach EOL yet, but it will happen sometime in the future, aka soon: https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

I think we should keep it for a while, maybe using Docker images could help.

**Comment by karliss** [comment]
Not having Ubuntu  18.04 or older also means problems for the compatibility of appimage. The way it works for best compatibility with as much distro as possible building on older distros is preferable.

**Comment by karliss** [comment]
Not relevant anymore, meaning of 18.04 has changed over the years

after  #3363 
there is now:
* qt5-systemdeps running on 18.04
* ubuntu 18.04 with qt5 cutter deps for Appimage
