### ISSUE TITLE
cutter/rizin wont start... error while loading shared libraries

### ISSUE THREAD

**Issue by dhucul** [rizinorg/cutter#2512]
/Cutter: error while loading shared libraries: librz_socket.so.4.6.0-git: cannot open shared object file: No such file or directory.
In fact "librz_socket.so.4.6.0-git" _is_ in the rizin directory.  I suspect cutter in still looking for the radare directory?

**Comment by Surendrajat** [comment]
@dhucul this is a documented issue in building docs: https://cutter.re/docs/building.html#troubleshooting

Also, please make sure to fill issue template from now on so everyone knows you're building from sources.

**Comment by ITAYC0HEN** [comment]
hi @dhucul! How did you try to build Cutter? We slightly updated the way we build Cutter and soon all the docs will be in place. In addition, Rizin is built different than radare2 but this should not affect you while building Cutter.

I suggest to make sure that the submodules of Rizin are there. Also, did you try to. compile it using Bundled Rizin or system rizin?

**Comment by dhucul** [comment]
cmake -DCMAKE_EXE_LINKER_FLAGS="-Wl,--disable-new-dtags"  ..worked. Thanks.
