### ISSUE TITLE
cutter can't be verified

### ISSUE THREAD

**Issue by fafg** [rizinorg/cutter#2515]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/9274235/102294508-c0847200-3f49-11eb-8ecf-e520fd1802ed.png">

Mac OS 11.1 (big sur)

**Comment by Surendrajat** [comment]
@fafg this is a known issue with unsigned apps on macOS. Check [this workaround](https://github.com/helm/helm/issues/6615#issuecomment-541706907) if it works for you. This is documented in [mac help docs](https://support.apple.com/en-in/guide/mac-help/mh40616/mac).

**Comment by ITAYC0HEN** [comment]
Thank you @fafg :) We are working to solve this problem, but it will take some time (and money). 
Please let us know if the workaround worked. Tanks!
I will close this issue in the meantime.

**Comment by ghostpepper108** [comment]
This is what worked for me

xattr -dr com.apple.quarantine "path to cutter app"
(sudo if required)

**Comment by layerlre** [comment]
> This is what worked for me
> 
> xattr -dr com.apple.quarantine "path to cutter app" (sudo if required)

Worked for me
