### ISSUE TITLE
Finish qmake removal

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2545]
**Is your feature request related to a problem? Please describe.**

After #2529 everything should be in a state where Cutter release can be made on all platforms without qmake. There is still room for further improvements in #2098 but those are not blockers. As a result of changes in Travis open source offering and move to rizinorg those old qmake CI scripts which partially relied on Travis usable anyway.

**Required changes**

- [ ]  Move the source file list directly to CMake, and do the same for other variables currently read from qmake project
- [ ]  Remove script for parsing qmake project
- [ ]  Remove qmake project
- [ ]  Remove references to qmake in docs
- [ ]  Decide what to do with meson build, it currently also reads values from qmake file.
- [ ]  deploy_translations.sh

**Comment by XVilka** [comment]
@ret2libc is the Meson expert, might give a good suggestion what to do with that.

**Comment by karliss** [comment]
I discussed it with @thestr4ng3r  and he agreed that there is no point keeping.
