### ISSUE TITLE
Ghidra Decompiler Error: No sleigh specification for x86:LE:32:default

### ISSUE THREAD

**Issue by PnthrLeo** [rizinorg/cutter#2548]
**Environment information**
* Operating System: windows 10
* Cutter version: 1.12.0
* File format: pe
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Ghidra cannot find sleigh specification for x86:LE:32:default

**To Reproduce**
1. Install cutter via  unzipping Cutter-v1.12.0-x64.Windows.zip
2. Run cutter.exe
3. Open binary from https://crackmes.one/crackme/5feae16d33c5d4264e590154
4. Set Ghidra decompiler 

![image](https://user-images.githubusercontent.com/29786176/103493367-e82c7300-4e41-11eb-9b69-88b2a1393d51.png)
![image](https://user-images.githubusercontent.com/29786176/103656839-27f67600-4f7a-11eb-9cc0-71a75bf04b9d.png)

**Comment by PnthrLeo** [comment]
Oh, I am so sorry. Problem was with a Russian letter 'C', which I accidently wrote in the name of Сutter's folder

**Comment by karliss** [comment]
If it isn't working in such situation I would still call it a bug path handling. It can be avoided and isn't the highest priority, but would be nice to fix.
