### ISSUE TITLE
Validate formatting on new PR and Push

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#2565]
**Describe the solution you'd like**

The PR on #2513 will add support for clang-format in Cutter. After it, we will need to validate that new commits are properly formatted. We can do it using a simple [github action](https://github.com/marketplace/actions/clang-format-check) or create a workflow by ourselves.

**Comment by karliss** [comment]
I have looked at the available clang format actions, most of them are more or less a shell script. That we might as well do ourselves.

As an ideal version I would consider something like CMake repository has. Where it complain if PR isn't well formatted, but it allows easily running the formatter by adding comment in PR. That seems like good balance between avoiding ruining code by automatically committing changes and being friendly for new and one time contributors.
Just having the validation part might also get annoying quickly even for regular contributors trying to do a quick fix.  This approach would probably require implementing custom action. Properly handling the permissions might be a bit tricky.
