### ISSUE TITLE
macOS icon changes after opening

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2575]
**Environment information**
* Operating System: macOS
* Cutter version:  bb6a9e2a913c051cadd5a26ab4e8b4c8f296100d
* Obtained from:
  - Downloaded from CI artifact

**Describe the bug**

After opening Cutter initially icon in taskbar shows the new icon from #2571 but then switches to the round icon used on rest of platforms.

**To Reproduce**

1. Download cutter dmg
2. Open Cutter.app
3. observe task bar

**Expected behavior**

macOS specif icon get's used at runtime.

**Screenshots**

**Additional context**

**Comment by thestr4ng3r** [comment]
Fixed in #2776
