### ISSUE TITLE
Investigate and fix command change

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2577]
**Is your feature request related to a problem? Please describe.**

Currently there is quite a few errors about json output not being valid or commands not being recognized. 

![image-cc0306f5-484c-4a13-84d7-d3c8bd79caeb](https://user-images.githubusercontent.com/7101031/105625277-8eabd880-5e30-11eb-9e63-1030fd72b5ca.jpg)

**Describe the solution you'd like**

* Try running Cutter preferrably with Linux, Windows and macOS executables
* See what errors show up
* Investigate the cause for each of them
    * command name changed -> update command call or replace with C API if available
    * command output is actually invalid json -> create a rizin issue

**Describe alternatives you've considered**

**Additional context**

**Comment by ITAYC0HEN** [comment]
fixed in https://github.com/rizinorg/cutter/pull/2579 ?

**Comment by karliss** [comment]
Not fully, some things were fixed by #2581 but there is at least one case of iCj where it prints invalid non whitespace text.

**Comment by XVilka** [comment]
Will be closed by https://github.com/rizinorg/cutter/pull/2630

**Comment by XVilka** [comment]
Closing since it was merged.
