### ISSUE TITLE
Windows building with Meson failed (script build.bat is not found)

### ISSUE THREAD

**Issue by gerhart01** [rizinorg/cutter#2587]
**Environment information**
* Operating System: Windows
* Cutter version: 1.12
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

According Building docs for building Cutter on Windows with Meson we need run:

CALL prepare_rizin.bat
CALL build.bat

but script build.bat doesn't present in repository.

**Comment by ITAYC0HEN** [comment]
Hey :)
Indeed the docs were outdated, I sent a PR to update them: https://github.com/rizinorg/cutter/pull/2590

Not only this, but we currently facing an issue that the docs are not updated on the website. We will work on fixing it soon.

**Comment by gerhart01** [comment]
Good, thanks.

  
>Четверг, 11 февраля 2021, 13:54 +03:00 от Itay Cohen <notifications@github.com>:
> 
> 
>Hey :)
>Indeed the docs were outdated, I sent a PR to update them:  #2590
>Not only this, but we currently facing an issue that the docs are not updated on the website. We will work on fixing it soon.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--
Gerhart X

**Comment by Surendrajat** [comment]
Docs are up to date now and the CI is in place to update it now on hence closing this one.
@gerhart01 Please try now and open a new issue if new instructions don't work for you.
