### ISSUE TITLE
Cannot save as rzdb project

### ISSUE THREAD

**Issue by Martyx00** [rizinorg/cutter#2597]
**Environment information**
* Operating System: Linux
* Cutter version: 1.12.1
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Cutter downloaded from GitHub releases does not offer me the option to save project as described here: https://rizin.re/posts/introducing-projects/#usage
This is likely due to it defaulting to use `r2` as a back-end (I would expect otherwise).

**To Reproduce**

1. Download Cutter v1.12.0 for Linux
2. Open any binary
3. Try to save as a project
4. Fail

**Expected behavior**

Cutter should allow saving work as `rzdb` project.

**Comment by ITAYC0HEN** [comment]
Hey @Martyx00! You mentioned "_Cutter version: 1.12.**1**_", did you mean for v1.12.0?

Cutter v1.12.0 release was published before the fork to Rizin and such Cutter recent release does not include the new Projects feature. However, it is already in the main branch here on Github and will be part of the upcoming release.

Thankfully, our CI compiles versions of Cutter any time we merge a Pull-Request so you can try download some of the CI artifacts and try the new Projects feature with them

For example: https://github.com/rizinorg/cutter/actions/runs/564184056
