### ISSUE TITLE
Improve function widget UI

### ISSUE THREAD

**Issue by xarkes** [rizinorg/cutter#2598]
**Is your feature request related to a problem? Please describe.**

The current function widget looks very poor:
![image](https://user-images.githubusercontent.com/10772605/107872397-6ac93900-6eaa-11eb-8509-c685dd796141.png)

**Describe the solution you'd like**

It appears that a very tiny icon makes the widget much more friendly and understandable in my opinion.
![image](https://user-images.githubusercontent.com/10772605/107872408-7d437280-6eaa-11eb-9422-f2cb3d291bf9.png)
I think designing/finding a free to use icon and show it in front of the functions would improve the UI.

**Describe alternatives you've considered**

None considered for now.

**Comment by jaskiratsingh2000** [comment]
Hey! I am interested to work on this issue. Is this issue still open up for commit?

**Comment by xarkes** [comment]
Hello,
Actually there is already a pending PR that we should merge so I would say no :-)
