### ISSUE TITLE
Feature Request: Custom Shortcut keys

### ISSUE THREAD

**Issue by tobias1012** [rizinorg/cutter#2612]
**Is your feature request related to a problem? Please describe.**

The possibility to setup own standards to accelerate personal workflow.

**Describe the solution you'd like**

Having a menu in preferences for assigning keyboard shortcuts.

**Describe alternatives you've considered**

Another alternative could be having such a list of shortcuts in a configuration file.

**Additional context**

None

**Comment by tobias1012** [comment]
In part related to #2554

**Comment by xarkes** [comment]
Hello, thanks for the suggestion!
There is already an issue regarding this topic: https://github.com/rizinorg/cutter/issues/2556
Therefore, I am closing this issue as a duplicate.
