### ISSUE TITLE
Graph not updated after editing control flow and re-analyzing.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2614]
**Environment information**
* Operating System: linuxmint 20.1
* Cutter version: 1.12.0
* File format: elf64
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Graph view does not update when changing instructions even after analyzing with `aaa`.

**To Reproduce**
1. Open elf binary with analysis `aaa`
1. Fully overwrite function with null-bytes
1. Re-analyze everything via console command `aaa`
1. Display function graph
1. See error

**Expected behavior**
Graph is updated / linearized by analysis of function.

**Screenshots**
![image](https://user-images.githubusercontent.com/19511852/109513937-dfed5e80-7aa5-11eb-9742-18533af368d2.png)

**Comment by wargio** [comment]
dup https://github.com/rizinorg/cutter/issues/2146
