### ISSUE TITLE
Test file extension before trying to load binary plugin

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2626]
**Is your feature request related to a problem? Please describe.**

Currently Cutter doesn't check file extensions when trying to load binary plugins. This  may result to warning like this when there are some additional files in plugin directory.
> Load Error for plugin "rz_ghidra_cutter.lib" : "Failed to extract plugin meta data from 'C:/Users/GTO/Desktop/cutter-upload-test-2-x64.Windows.zip/cutter-upload-test-2-x64.Windows/plugins/native/rz_ghidra_cutter.lib'"

In this specific case the specific lib file doesn't need to be there, but there could be various other situations resulting in additional  files in plugin directory.

Actually loading something that isn't a plugin is unlikely even for files that are dynamic libraries, since it uses Qt for checking metadata with Cutter plugin identifier. This is mostly question of not having unnecessary warnings in output log.

**Describe the solution you'd like**

Code that loads binary plugins checks the file extension before trying to load plugin. Ignore files that don't have dynamic library extension. If available use Qt define for the current platform dynamic library extension instead of creating a new one. That way there is less platform specific code within Cutter and making porting to any platform with Qt support easier.

**Describe alternatives you've considered**

**Additional context**

**Comment by Mamograg17** [comment]
Can I know which files extension is the accepted ? Just trying to solve this problem.

**Comment by ret2libc** [comment]
Maybe using https://doc.qt.io/qt-5/qlibrary.html#isLibrary is enough to fix this?

**Comment by wargio** [comment]
that lib file needs to be removed from the install location.
