### ISSUE TITLE
Bug report template (in Cutter GUI) contains too many blanks in the list.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2632]
**Environment information**
* Operating System: linuxmint 20.1
* Cutter version: 1.12.0
* File format: any
* Arch: any
* Type: any

**Describe the bug**
Bug report template contains too many blanks in the list.

**To Reproduce**
1. Click on `menu bar > help > report an issue`
2. See error

**Expected behavior**
Well formated template.

**Screenshots**
![image](https://user-images.githubusercontent.com/19511852/110664379-a2848180-81c7-11eb-8b43-b242af9b5a12.png)

**Comment by karliss** [comment]
It got a lot better in #2808 . Only thing that I would say is currently bad is having built from source checked by default.

**Comment by karliss** [comment]
![image](https://user-images.githubusercontent.com/7101031/184082401-d636566a-d228-418a-9920-d963952a6584.png)
