### ISSUE TITLE
Update the issue template in BugReporting.cpp to match bug_report.md

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2633]
**Is your feature request related to a problem? Please describe.**
Recently I have been asked to provide the source of the code (Build from source / appimage / ...).

**Describe the solution you'd like**
When reporting a bug from within the app automatically mention whether it has been build from source, downloaded (appimage), etc.

**Comment by karliss** [comment]
It is already in the template

**Comment by ITAYC0HEN** [comment]
Food catch ;)
Would you like giving it a try?
