### ISSUE TITLE
Colon in the function search bar changes the list formatting.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2639]
**Environment information**
* Operating System: linuxmint 20.1
* Cutter version: 1.12.0
* File format: elf64
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Typing a colon in the function search bar changes the list formatting (increases line height / distance).
It is reversible.

**To Reproduce**
1. Open a large binary with multiple functions
1. Type a `:` in the function search bar
1. See error

**Expected behavior**
Display functions according to the search text without changing the format of the list.

**Screenshots**
Both screenshots merged side by side for nice comparison of line height.
![image](https://user-images.githubusercontent.com/19511852/111191178-1653cf00-85b8-11eb-9ef7-802aa88338a5.png)

**Comment by ITAYC0HEN** [comment]
I can't reproduce with the binaries I have, and with Cutter built from git

**Comment by Semnodime** [comment]
There is no error in the console.
I just noticed that the bug does not only happen by typing the `:` but also with the `a`, `b`, `d`, `e`, `g`, `h`, `j`, `k`, `l`, `o`, `p`, `q`, `r`, `u`, `v`, `w`, `x`, `z`.
It is always the same letters.

I'll restart Cutter and load the same binary just to be sure.

**Comment by Semnodime** [comment]
Cannot reproduce after restarting Cutter.
Issue remains for archival purpose in case this bug reappears.

...Guess that's one of those bugs that is best dealt with by restarting your IDE then.

**Comment by ITAYC0HEN** [comment]
Haha very interesting! Maybe tis At bug, we won't know untill someone will reproduce.
Thank you for everything, as usual
