### ISSUE TITLE
Cutter 2.0 cannot work on MacOS mojave

### ISSUE THREAD

**Issue by AlexsanderShaw** [rizinorg/cutter#2648]
**Environment information**
* Operating System: MacOS mojave
* Cutter version: 2.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: dmg

**Describe the bug**

1. Download dmg image from release
2. Double click dmg file 
3. See error: The app icon is gray, shows the app cannot work on the os version

**Expected behavior**

app should install sucessfully and work well

**Screenshots**

![image](https://user-images.githubusercontent.com/18108607/112927634-e5db6b80-9147-11eb-802e-01a390ac888a.png)

**Additional context**

Cutter Version 1.12 is work well, and 2.0 on MacOS big sur is work well too.

**Comment by therealprof** [comment]
Fun fact, it actually does work on Mojave if you use `cutter.wrapper.sh` or call it directly via `/Applications/Cutter.app/Contents/MacOS/Cutter`.

**Comment by AlexsanderShaw** [comment]
> Fun fact, it actually does work on Mojave if you use `cutter.wrapper.sh` or call it directly via `/Applications/Cutter.app/Contents/MacOS/Cutter`.

Yep, I tried the method, cutter can start succefully.

**Comment by karliss** [comment]
@AlexsanderShaw Could you test the build from this PR https://github.com/rizinorg/cutter/pull/2650 download links should be here https://github.com/rizinorg/cutter/actions/runs/712842706

**Comment by therealprof** [comment]
> @AlexsanderShaw Could you test the build from this PR #2650 download links should be here https://github.com/rizinorg/cutter/actions/runs/712842706

Does work great for me on Mojave. 👍

**Comment by AlexsanderShaw** [comment]
> @AlexsanderShaw Could you test the build from this PR #2650 download links should be here https://github.com/rizinorg/cutter/actions/runs/712842706

Great, it works well on Mpjave now! 👍
