### ISSUE TITLE
Cutter Freezing when loading, searching in large projects

### ISSUE THREAD

**Issue by CXCubeHD** [rizinorg/cutter#2660]
**Environment information**
* Operating System: windows 10
* Cutter version: 2.0.0
* File format: pe64
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Cutter FREEZES a lot when:
- Loading a big file
- Searching for stuff
- Saving the project
(this mostly applies for big files)

**To Reproduce**
1. Open a big file (aroud 60mb)
2. Do the stuff mentioned above

**Expected behavior**
No freeze. Cutter should cancel the searching task when another character is typed in the search box

**Additional context**
Dear Cutter Team, you make so cool stuff, BUT WHY! Just move the searching stuff to another thread so that the window is still responive! You guys are so skilled but you can't really fix a simple issue. (btw I have posted this 5 months ago and nobody fixed it...)

**Comment by xarkes** [comment]
Yeah thanks for reporting, it's more or less a known issue.
I'm pretty busy IRL so I can't really find time to address this issue at the moment, but feel free to give it a try! :wink:

The mentioned previous issue: https://github.com/rizinorg/cutter/issues/2487
Should probably be split in two issues (one for project, one for search)
