### ISSUE TITLE
Process attach dialog doesn't resize properly

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2665]
**Environment information**
* Operating System: Arch Linux
* Cutter version: 2.0.1 + changes in #2662
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: N/A

**Describe the bug**

When increasing size of window table size doesn't increase. When decreasing window size table scrollbar gets cut off. 

**To Reproduce**

1. Open process attach dialog

**Expected behavior**

Table resizes together with window.

**Screenshots**

![image](https://user-images.githubusercontent.com/7101031/114743378-4fb56100-9d55-11eb-8a79-80321f0fb73e.png)

**Additional context**

**Comment by AdavisSnakes** [comment]
I'll take a look at this issue
