### ISSUE TITLE
Some of the color themes are not listed

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#2672]
**Environment information**
* Operating System:
* Cutter version: 2.0.1
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Settings color theme selection lists less color themes than `ecoj`.  Cutter has a hardcoded list of which color themes are considered dark and light, but there seems to be code for handling unknown themes.

**To Reproduce**

1. Go to Preferences/Appearance
2. note all the color themes when light interface is chosen
3. 2. note all the color themes when dark interface is chosen
4. type `ecoj` in console widget to list all the included themes

**Expected behavior**

All color themes included in the official package can be selected in "Appearance/Color Theme".

**Screenshots**

**Additional context**

**Comment by rever1and** [comment]
doesnt it is intended to have hardcoded color themes for dark/light interface?

**Comment by karliss** [comment]
I expect the hardcoded lightness mapping to remain there but the themes for which it is unknown should be displayed in both lists instead of not being listed at all. As I noted in the description parts of code are already written with assumption that there can be additional themes with unknown lightness, probably to deal with user themes.
