### ISSUE TITLE
Defining a String as Code or Data should remove the String

### ISSUE THREAD

**Issue by AlfHou** [rizinorg/cutter#2690]
**Environment information**
* Operating System: macOS (10.14.6)
* Cutter version: 2.0.2
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository: Homebrew
* File format: binary x86_64 ELF

## Modified content
When a strings is defined in the disassembly, using <kbd>A</kbd>, the only option to remove it is with  `Right Click -> Set As -> String -> Remove`. However, it is not very user-friendly and it would be much better if pressing `C` or `D` (define this as Code or Data) will remove the defined string and define these addresses to Code or Data as chosen by the user.

To demonstrate — If a user accidentally presses <kbd>A</kbd> they will define some code as String. In the new solution, pressing <kbd>C</kbd> will remove the accidentally defined string and will re-define these addresses to Code again.

---

<details>
  <summary>Original post, Click to expand.</summary>
  
I accidentally pressed the 'A' key on my keyboard, making the instruction under my cursor be interpreted as a string
instead of a regular instruction. Neither `cmd+Z`, `ctrl+Z`, pressing 'C' nor right click->Set as...->Code makes it go back to where it was. 

**To Reproduce**
Either press the 'A' button, or right-click->Set as...->String...->Auto Detect on an instruction, then try to revert it back to the instruction.

**Expected behavior**
Either it shoud be easier to undo a just done instruction, or conversion between instruction <-> string should be fixed

</details>

**Comment by ITAYC0HEN** [comment]
I agree that marking this as Code\Data should remove and override the string.
That said, what happens if you do the following?
Right Click -> Set As -> String -> Remove

**Comment by AlfHou** [comment]
>Right Click -> Set As -> String -> Remove
I can confirm that this resloves the issue. 
It feels a little unintuitive however.

**Comment by ITAYC0HEN** [comment]
Happy to know that it resolves the issue. I agree with you that it's not the best way.
Thus, I will modify the title&content your issue to be a feature-request that we can track :)
