### ISSUE TITLE
librz_core.so not found

### ISSUE THREAD

**Issue by Umiko56** [rizinorg/cutter#2696]
**Environment information**
* Operating System: Linux arch-laptop 5.12.6-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 23 May 2021 00:45:48 +0000 x86_64 GNU/Linux
* Cutter version: Unable to run cutter -v
* Obtained from:
  - [x] Built from source

**Describe the bug**
First of all excuse me if my english is not perfect.
I tried running cutter, but it looks like it doesn't find the *librz_core.so.0.2.0* shared library. Where can I find this .so ? Where to put it ? 
I also tried reinstalling rizin, without succes. 

**Expected behavior**

I just wanted to run Cutter

**Screenshots**

![last_screenshot](https://user-images.githubusercontent.com/77581990/119632663-508be900-be11-11eb-9742-f922a7c81b69.jpg)
![last_screenshot](https://user-images.githubusercontent.com/77581990/119632734-600b3200-be11-11eb-9e49-67bce9d08906.jpg)

Thanks. I hope you will find how to help me.

**Comment by xarkes** [comment]
Hello, could you please provide the options you used to compile Cutter?

**Comment by XVilka** [comment]
Closing since there is no response for more than a year, we had multiple releases since, and provided information is insufficient. Open a new issue with more details, if you still meet it.
