### ISSUE TITLE
Crashes when viewing msvc pe libraries in disasm view

### ISSUE THREAD

**Issue by riesha** [rizinorg/cutter#2700]
**Environment information**
* Operating System: windows 10
* Cutter version: 2.0.2
* File format: pe
 * Arch: x86
 * Type: DLL (Dynamic Link Library)

**Describe the bug**
Crashes when in disasm view when opening x86 game libraries

**To Reproduce**
open these binaries with aaa + import demanged symbols + virtual addressing. (everything set to auto otherwise)

**Expected behavior**
Being able to reverse these binaries without crashing

**Screenshots**
type 1
![image](https://user-images.githubusercontent.com/58556779/120082335-a804b000-c0c2-11eb-9a29-1472000020c2.png)
type 2
![image](https://user-images.githubusercontent.com/58556779/120082327-a0dda200-c0c2-11eb-9a59-93a4aa94e65d.png)

**Additional context**
[cutter_crash_info.zip - contains 6 crash dumps and the 2 binaries](https://github.com/rizinorg/cutter/files/6565221/cutter_crash_info.zip)

If you need any additional info please tell me this is my first time formally writing one of these

**Comment by xarkes** [comment]
I didn't check the stacktrace yet, but it might be related to https://github.com/rizinorg/cutter/pull/2688

**Comment by thestr4ng3r** [comment]
https://github.com/rizinorg/rizin/pull/1718 also applies here. This might indeed be fixed and needs to be re-tested.

**Comment by XVilka** [comment]
Tried to reproduce on Linux - crash doesn't happen anymore.
