### ISSUE TITLE
update checker incorrectly shows 1.12.0 as up to date

### ISSUE THREAD

**Issue by psifertex** [rizinorg/cutter#2707]
**Environment information**
* Operating System: MacOS 11.4
* Cutter version: 1.12.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository

**Describe the bug**

Checking if updates are available on this release  is broken

**To Reproduce**

1. Go to the about dialog
2. Click on "Check for updates"

**Expected behavior**

I should be told an update is available (2.0.2 is the latest built release currently).

**Screenshots**

<img width="622" alt="Screen Shot 2021-06-23 at 9 14 57 AM" src="https://user-images.githubusercontent.com/140215/123103375-eeb8a200-d403-11eb-9fa6-c9711e897d1a.png">

**Comment by ITAYC0HEN** [comment]
Thanks @psifertex! We will look into it :)

**Comment by XVilka** [comment]
One year after and multiple 2.0 releases, do you think it still relevant? 
On the other hand, I checked with the 2.0.4 version after 2.0.5 was released and got API limit error:

![image](https://user-images.githubusercontent.com/203261/149650263-e8ebaf3a-f377-4e51-9316-643ecdd41e5b.png)

**Comment by psifertex** [comment]
Yeah, looks like the original issue is long since resolved -- closing.

As to the other point you bring up, the issue being run into is: https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#authentication

In short, unauthenticated clients are rate-limited to API queries so someone either 1) running multiple applications using those APIs, or 2) behind any IP NAT that might be aggregating multiple users network traffic could easily trigger it.

To get around it with the Binary Ninja plugin manager that uses releases as well for many different projects, we use an [authenticated plugin](https://github.com/Vector35/community-plugins/blob/master/generate_index.py) to generate a static [json file](https://github.com/Vector35/community-plugins/blob/master/plugins.json) with all of the metadata we need so that our plugin manager can simply check that static file. It's less API load but you'd need to integrate either a GH action or manually generate it for each release.

Hope that helps!

**Comment by psifertex** [comment]
Oh, I should also clarify that another possible fix is to of course register and authenticate your application using an oauth token or some other means but that seems rather overkill just for update checking. :-)
