### ISSUE TITLE
Remote debugging with gdb server causes crash on MacOS

### ISSUE THREAD

**Issue by PulakIIIT** [rizinorg/cutter#2708]
**Environment information**
* Operating System: MacOS Catalina 10.15.7
* Cutter version: Dev branch
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: Linux 64 bit binary

**Describe the bug**
As soon as I click on `ok` on the remote debugging configuration dialog box, Cutter crashes. 

**To Reproduce**

1. Start a gdb server
2. Open the same binary on Cutter on MacOS and go to Debug menu -> Connect to a remote debugger
3. In the remote configuration dialog box enter the IP and port. 
4. Click OK (Cutter should crash)

**Expected behavior**

Cutter should not crash and remote debugging should work.

**Screenshots**
Gdbserver: 
<img width="731" alt="Screenshot 2021-06-27 at 10 36 11 AM" src="https://user-images.githubusercontent.com/56169176/123533464-846d6d80-d733-11eb-8e53-bf37992774c2.png">
Backtrace:
<img width="535" alt="Screenshot 2021-06-27 at 10 37 54 AM" src="https://user-images.githubusercontent.com/56169176/123533500-c7c7dc00-d733-11eb-8800-ddb8d47e8a3f.png">
Seems like `relocs` is NULL: 
<img width="959" alt="Screenshot 2021-06-27 at 10 39 32 AM" src="https://user-images.githubusercontent.com/56169176/123533539-f9d93e00-d733-11eb-9643-1140bd354811.png">

**Additional context**

**Comment by xarkes** [comment]
Thanks for the detailed report! :)
