### ISSUE TITLE
cutter crash when attach to debug process

### ISSUE THREAD

**Issue by peach-lasagna** [rizinorg/cutter#2715]
**Environment information**
* Operating System: Windows 10
* Cutter version: 2.0.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: elf 64-bit

**To Reproduce**

1. Debug > Attach to process
2. ![изображение](https://user-images.githubusercontent.com/59787538/125177347-38c3c500-e205-11eb-9ce0-feaa1c28895a.png)

**Comment by xarkes** [comment]
Is it the case for any executable?

**Comment by peach-lasagna** [comment]
> 
> 
> Is it the case for any executable?

yes

**Comment by crass** [comment]
That seems odd, you're running an Elf64 version of Cutter on Windows 10? Perhaps that has something to do with it?

**Comment by peach-lasagna** [comment]
> 
> 
> That seems odd, you're running an Elf64 version of Cutter on Windows 10? Perhaps that has something to do with it?

![изображение](https://user-images.githubusercontent.com/59787538/129175053-9406d26d-e023-4033-accb-564f1d48887b.png)
no.

**Comment by xarkes** [comment]
Could reproduce with latest release, didn't have a debug version in order to generate a stacktrace.

**Comment by crass** [comment]
> > That seems odd, you're running an Elf64 version of Cutter on Windows 10? Perhaps that has something to do with it?
> 
> ![изображение](https://user-images.githubusercontent.com/59787538/129175053-9406d26d-e023-4033-accb-564f1d48887b.png)
> no.

Ok, maybe I misunderstood the meaning of "File Format" in the "Environment" section. I've assumed that meant the file format of the Cutter binary. Perhaps it means the file format of the binary that Cutter is analyzing when the issue occurs.

**Comment by peach-lasagna** [comment]
> 
> 
> > > That seems odd, you're running an Elf64 version of Cutter on Windows 10? Perhaps that has something to do with it?
> > 
> > 
> > ![изображение](https://user-images.githubusercontent.com/59787538/129175053-9406d26d-e023-4033-accb-564f1d48887b.png)
> > no.
> 
> Ok, maybe I misunderstood the meaning of "File Format" in the "Environment" section. I've assumed that meant the file format of the Cutter binary. Perhaps it means the file format of the binary that Cutter is analyzing when the issue occurs.

cutter crashes on any file format.

**Comment by wyattearp** [comment]
FYI - was also able to cause this same issue running on Linux x64 (latest ubuntu 20.04), using `Cutter-v2.0.2-x64.Linux.AppImage` and crashed for both attaching to a process and attaching to a remote process in GDB.

**Comment by thestr4ng3r** [comment]
This seems to be fixed. On Windows I can easily reproduce it with the 2.0.2 release, but with the https://github.com/rizinorg/cutter/runs/3689923736 artifact everything works fine. I can't debug the old crash though due to lack of a dev environment on windows.
