### ISSUE TITLE
Is it possible to add feature of loading library dependency, since `LD_LIBRARY_PATH` have to be empty when boot.

### ISSUE THREAD

**Issue by Shoreshen** [rizinorg/cutter#2719]
I have to debug a program that is depending on list of so files.

I used to add them in `LD_LIBRARY_PATH` variable so that they will be loaded automatically.

However, when I switch to cutter, I couldn't find an option of adding dependency files, and the `LD_LIBRARY_PATH` have to be empty for me to start it.

I've searched over the internet and the help documentation, but cannot find any way.

And if there is a way, can it be added into the doc, so that people need it can be referenced

**Comment by xarkes** [comment]
Hello,
I am not sure to understand the issue here. Are you in a debugging scenario?

**Comment by xarkes** [comment]
Have you managed to solve your issue?
For now it is not possible to specify environment variables while debugging, but it could be a feature to add to the debugger.
I think you can manage to do what you want with `LD_LIBRARY_PATH`, unless your debugged program uses libraries that are also used by Cutter but with a different version which would break Cutter.

**Comment by Shoreshen** [comment]
Hi I did it by adding start script for the program~~~lol, so I actually closed the case since it is solved for me.......
