### ISSUE TITLE
Failed to parse JSON when loading certain rzdb

### ISSUE THREAD

**Issue by crass** [rizinorg/cutter#2730]
**Environment information**
* Operating System: Ubuntu 20.04 AppImage
* Cutter version: 2.0.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: Windows PE format

**Describe the bug**

When loading Cutter with the attached rzdb using the AppImage, the following lines are output to stderr/stdout
```
Failed to parse JSON: illegal value
Fatal error. Cannot use RZ_HOME_DATADIR or JSDEC_HOME.
```

**To Reproduce**

1. Put attached binary and rzdb files in same directory.
2. Run `Cutter-v2.0.2-x64.Linux.AppImage -p EP0000551520.exe.2420128.exe.3.rzdb`
3. See outputted lines.

**Expected behavior**

Expect to not see those messages.

**Additional context**

I found the offending line in the rzdb which causes these error messages. Here is a zip of the binary and two rzdb files, one with the offending line and one without (the one with "no-error" in the name). The binary has been truncated to allow upload to github, but that doesn't appear to affect reproducing this issue.
[EP0000551520.zip](https://github.com/rizinorg/cutter/files/6986104/EP0000551520.zip)

**Comment by ret2libc** [comment]
I can't reproduce on Rizin, so might be a cutter-only issue.

**Comment by DMaroo** [comment]
Unable to reproduce on Cutter built using current master (62ecf3fb2a79e613d11392088851e0e83900f9bd). Both the projects open in Cutter without any errors on the console.

**Comment by xarkes** [comment]
Thanks, feel free to reopen if needed.
