### ISSUE TITLE
Breakpoints are not saved

### ISSUE THREAD

**Issue by waeladel** [rizinorg/cutter#2735]
**Environment information**
* Operating System: windows 10
* Cutter version: 2.0.2
* File format: pe
 * Arch: x86
 * Type: EXEC (Executable file)

**Describe the bug**
Breakpoints are not saved to the project.

**To Reproduce**
1. Add a breakpoint.
2. Save the project.
3. Close the project.
4. Re open the same project.

**Expected behavior**
To have all breakpoint in the breakpoint window.

**What acutely happens**
No breakpoints in the breakpoint window.

**Comment by ret2libc** [comment]
I think this is a dup of https://github.com/rizinorg/rizin/issues/707 ? Anyway, it's a problem in Rizin AFAIK, because breakpoints are not saved yet.
