### ISSUE TITLE
Ghidra decompilation doesn't reach expected quality 

### ISSUE THREAD

**Issue by rmast** [rizinorg/cutter#2737]
**Environment information**
* Operating System:
* Cutter version: 2.0.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

The quality and duration of the Ghidra decompilation is far below the quality of the decompilation of Ghidra 10.0.2.

**To Reproduce**

Compare the length of decompiled functions from a PE32 binary. Official Ghidra decompilation ends with 10% less lines and better specified details.

**Expected behavior**

I expect the durations of the default decompilation to take as much time as Ghidra does, and provide the same results.
It seems like a lot of default analyzing is skipped for speed reasons.

**Comment by thestr4ng3r** [comment]
Sorry, but this issue description provides no value to work on.
If you can pinpoint your problems to concrete aspects of the analysis in https://github.com/rizinorg/rizin or the decompilation in https://github.com/rizinorg/rz-ghidra, feel free to open an issue there and we can discuss possible ways to improve.
