### ISSUE TITLE
Unable to change rflags register value

### ISSUE THREAD

**Issue by ezra100** [rizinorg/cutter#2763]
**Environment information**
* Operating System: ubuntu 20.04
* Cutter version: 2.0.2
* File format: elf64
 * Arch: x86
 * Type: DYN (Shared object file)

**Describe the bug**
Can't change the value of the rflags register.
Instead of changing the value it gets changed to 0x202 no matter what I type in.
Tried also to change it via Rizin console, with `ar rflags = 0x...` it worked, with  `dr rflags = 0x...` it didn't.

**To Reproduce**

- Start cutter with any file and run the debugger
- Pause the debugger on some breakpoint
- In the registers window - click on the 'rflags' value field
- Enter some value (e.g. 0x242 while current value is 0xa02)
- Press enter

**Expected behavior**
The value of the rflags should change to the entered value (0x242 in our case)

**Screenshots**

Before:
![image](https://user-images.githubusercontent.com/3751364/133795424-d25f1ddd-e69a-4999-81ce-309d4c1f9d78.png)
After entering 0x246 in the rflags value field:
![image](https://user-images.githubusercontent.com/3751364/133795493-01a0feef-a4c3-4a36-9fe0-018872cad7de.png)

And via console:
dr - doesn't work:
![image](https://user-images.githubusercontent.com/3751364/133795810-f17145f7-6a09-40c0-8586-9a8382b540e4.png)

ar - works:
![image](https://user-images.githubusercontent.com/3751364/133795909-dc83fd5f-71cc-4a59-a731-69b8885df177.png)

**Additional context**

**Comment by ezra100** [comment]
Closing this since the Rizin issue was fixed
Thanks guys 🙏

**Comment by XVilka** [comment]
Requires Rizin submodule updated to at least https://github.com/rizinorg/rizin/commit/d6ac6b93ef999d906b20dd9d6116d220bf8df5c8 commit.

**Comment by ezra100** [comment]
Ok, I'm leaving it open then

**Comment by XVilka** [comment]
It was fixed sometime ago - works in the latest release and current `dev`.
