### ISSUE TITLE
Rizin Plugin Information for Bin, IO and Core is broken

### ISSUE THREAD

**Issue by thestr4ng3r** [rizinorg/cutter#2764]
In About Cutter -> Show Rizin plugin information, these lists should be filled:
<img width="751" alt="Bildschirmfoto 2021-09-18 um 10 29 31" src="https://user-images.githubusercontent.com/1460997/133882382-1280563a-8ac1-44fe-88f6-eaa6955815be.png">

**Comment by XVilka** [comment]
It could be done by accessing the plugins information [directly using the API](https://github.com/rizinorg/cutter/issues/2666) instead of those:
```
2578:    QJsonObject jsonRoot = cmdj("iLj").object();
2606:    QJsonArray plugins = cmdj("oLj").object()["io_plugins"].toArray();
2630:    QJsonArray plugins = cmdj("Lcj").array();
```

See `rz_core_bin_plugin_print()` implementation in `librz/core/cbin.c`, for example.
