### ISSUE TITLE
Arrows (X-references) not updated after function redefinition.

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#2854]
**Environment information**
* Operating System: linuxmint 20.2
* Cutter version: 2.0.3
* File format: elf64
 * Arch: x86
 * Type: 

**Describe the bug**
Undefining and redefining the function won't remove obsolete reference arrows within the disassembly tab.
Even after `View>Refresh Contents` the arrows won't disappear.

**To Reproduce**
Sadly I cannot provide an example to reproduce this bug publicly.

**Expected behavior**
No arrows starting at any of the `nop`s.

**Screenshots**
![image](https://user-images.githubusercontent.com/19511852/146506718-a709ffd8-5a6d-4cdd-934a-d09c489bcfba.png)

**Comment by XVilka** [comment]
It should be fixed already. Feel free to open a new issue if this still happens
