### ISSUE TITLE
Crash on startup when starting cutter from cmd.exe or wt.exe

### ISSUE THREAD

**Issue by segevfiner** [rizinorg/cutter#2877]
**Environment information**
* Operating System: windows 10
* Cutter version: 2.0.4
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: 
 * Arch: N/A
 * Type: N/A

**Describe the bug**

Crash on startup when starting cutter from cmd.exe or wt.exe (Windows Terminal) & PowerShell 7.2.1 on Windows 10.0.19044.0.

**To Reproduce**

1. Start `cutter` from either `cmd` or `wt` without any additional arguments.

**Expected behavior**

It shouldn't crash...

By the way? What's up with the weird start cutter from console to redirect output prompt? It shouldn't really be necessary to start a program from a console to redirect stdin/stdout/stderr, you can reassign them even if not started from the console as far as I'm aware. Just note that Python and other code grabs them on startup, so they should be initialized early enough.

**Additional context**

[Cutter_crash_dump_12.01.22_19.54.53.zip](https://github.com/rizinorg/cutter/files/7856672/Cutter_crash_dump_12.01.22_19.54.53.zip)

**Comment by ITAYC0HEN** [comment]
CC @yossizap for console redirection

**Comment by segevfiner** [comment]
Do you publish or own the PDB files for the release builds anywhere so the crash dump can be diagnosed?

BTW, to make stdio work with `/SUBSYSTEM:WINDOWS` without launching from a console (So `AttachConsole` fails) you probably just need to `fdopen` and overwrite the current stdio streams to working ones (You can just assign a different `FILE*` to them, though you might want/need to `fclose` them first), and you could use `open("NUL", ...)` to get some fd to set the stdio fds to something temporarily if needed for any library that checks for them.

One guess could be specifying `FILE_FLAG_OVERLAPPED` here: https://github.com/rizinorg/cutter/blob/8cc4d14a6fe0b1a0ce6baf2a2f280342eed64e0c/src/widgets/ConsoleWidget.cpp#L462-L463, as I think the CRT needs a non-overlapped handle, or maybe there is some other unchecked error somewhere leading to UB. Can't check exactly without debug symbols.

**Comment by segevfiner** [comment]
You crash here https://github.com/rizinorg/cutter/blob/91d99ba2190f4796da268be376d9f06e3c7f31bc/src/widgets/ConsoleWidget.cpp#L454
Because `fileno(stdin)` is `-2` as cutter is built with `/SUBSYSTEM:WINDOWS` and hasn't set `stdin` to anything after calling `AttachConsole`. Honestly, you should be able to redirect them even when cutter is not attached to a console by just setting them to `NUL` or something else appropriate if you want the `fdopen` for saving the orig handles to not fail, or even just acknowledge that there are no original handles.

And of course, any such stdio init should be done before anything that grabs/uses stdio itself, such as Python init, or rizin itself.
