### ISSUE TITLE
Enable console redirection on Windows without starting from a console

### ISSUE THREAD

**Issue by segevfiner** [rizinorg/cutter#2891]
**Is your feature request related to a problem? Please describe.**

Console redirection on Windows only works when started from a console.

**Describe the solution you'd like**

It should work even when not started from a console.

**Describe alternatives you've considered**

Deal with it. 😎 

**Additional context**

P.S. You should also consider not calling AttachConsole as that is unexpected for a GUI app on Windows, it causes cutter to print to the console while the prompt is still active (The console doesn't block on /SUBSYSTEM:WINDOWS applications), and I think it causes cutter to close when the console window is closed. Wireshark, which faced a similar issue, has implemented a configuration setting to call AllocConsole instead, which cutter can also do via either configuration or a CLI flag. (It's still useful to be able to allocate a console for any early output that cutter might print).

Wireshark's implementation (GitHub mirror):
* https://github.com/wireshark/wireshark/blob/0bc39aa2eb4992f66238bc6ee312e82e3a60017e/ui/win32/console_win32.cpp#L96-L192
* https://github.com/wireshark/wireshark/blob/7afb52c4793208728d82e4bf13f48304e3e9fbea/ui/console.c#L31-L38

(So apparently they do attach the an existing console if available, it's not a must, a you can always `AllocConsole` if you want to or even provide a setting, they do mention there is sometimes a need to call `FreeConsole` even when you think you don't need to)

cc @yossizap

**Comment by ITAYC0HEN** [comment]
@yossizap @segevfiner if this issue supposed to contain an improvement idea that isn't solved by #2888 then please re-open this issue and modify its contents and title <3
