### ISSUE TITLE
NX bit and PIC missing from Dashboard

### ISSUE THREAD

**Issue by RazviOverflow** [rizinorg/cutter#2895]
**Environment information**
* Operating System: Linux kali 5.15.0-kali2-amd64 1 SMP Debian 5.15.5-2kali2 (2021-12-22) x86_64 GNU/Linux (Kali 2021.4)
* Cutter version: Cutter v2.0.5-x64.Linux (AppImage)
* Obtained from:
  - [ ] Built from source
  - [X] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF 64-bit LSB executable

**Describe the bug**

The latest version of Cutter fails to detect a given binary's protection. Cutter does not seem to be able to detect whether NX bit and PIC protections are present. 

**To Reproduce**

1. Open a binary (ELF, in my case) file with Cutter.
2. Go to `Dashboard`.
3. See missing protections.

**Expected behavior**

In previous versions of Cutter all the information was displayed correctly. The latest version always states N/A.

**Screenshots**
![image](https://user-images.githubusercontent.com/41084837/153184398-275e0be2-e422-4dbd-b6cf-c3c559d49a08.png)

**Comment by bassuniz** [comment]
Hi
I am trying to work on this issue. could you provide the binary that you tested the correct expected output?

**Comment by RazviOverflow** [comment]
The binary doesn't really matter, the (unwanted) behavior is the same. Regardless of the binary.

I created a simple, toy binary that just prints a string to stdout. Compiled it with default flags `gcc $sourcecode.c`. When opening it with cutter, the protections are N/A, even though `checksec` is able to read them. 

Dashboard from Cutter:
![image](https://user-images.githubusercontent.com/41084837/159039035-9fbddaf0-9e97-4516-9da3-214eb7d38fa0.png)

Output from `checksec`:
```
$ checksec --file=a.out        
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH   Symbols         FORTIFY Fortified       Fortifiable     FILE
Partial RELRO   No canary found   NX enabled    PIE enabled     No RPATH   No RUNPATH   40) Symbols    No    0               1               a.out  
```

The code I compiled was:
```c
#include<stdio.h>
void main(){
	printf("Will NX/PIC appear?");
}
```

**Comment by bassuniz** [comment]
> The binary doesn't really matter, the (unwanted) behavior is the same. Regardless of the binary.
> 
> I created a simple, toy binary that just prints a string to stdout. Compiled it with default flags `gcc $sourcecode.c`. When opening it with cutter, the protections are N/A, even though `checksec` is able to read them. 
> 
> Dashboard from Cutter:
> ![image](https://user-images.githubusercontent.com/41084837/159039035-9fbddaf0-9e97-4516-9da3-214eb7d38fa0.png)
> 
> Output from `checksec`:
> ```
> $ checksec --file=a.out        
> RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH   Symbols         FORTIFY Fortified       Fortifiable     FILE
> Partial RELRO   No canary found   NX enabled    PIE enabled     No RPATH   No RUNPATH   40) Symbols    No    0               1               a.out  
> ```
> 
> The code I compiled was:
> ```c
> #include<stdio.h>
> void main(){
> 	printf("Will NX/PIC appear?");
> }
> ```

Great, I will look into that.
