### ISSUE TITLE
Cutter fails to find themes directory

### ISSUE THREAD

**Issue by yossizap** [rizinorg/cutter#2897]
**Environment information**
* Operating System: Windows 10 and Ubuntu 20.04
* Cutter version: latest - 1b271a0 
* Obtained from:
  - [x] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

Cutter fails to load rizin themes after searching for the them in the original build directory path(`RZ_PREFIX`) instead of using the relative path due to changes in `rz_path_prefix` on rizin's side.

**To Reproduce**

Download the latest windows build artifact or build from source with bundled Rizin and rename the build folder before running Cutter.
This issue isn't reproducible with the Linux AppImage.

**Expected behavior**

The themes folder path should be portable.

**Screenshots**

![Capture1234](https://user-images.githubusercontent.com/5659696/153728853-5693618f-fcfb-4024-96b4-fca7f197dc1a.PNG)

**Additional context**

Themes fail to load even after switching to `QCoreApplication::applicationDirPath` instead of `rz_path_prefix` since `rz_core_themes_load` also uses rizin's path functions to find the themes. Also, the rizin folders are installed differently in linux and windows, they should be in the same path.

**Comment by ret2libc** [comment]
@yossizap I think this was not solved by the changes in rizin, was it?

@wargio is looking at it as well. What I found is that:
```c
	char *bindir = rz_path_realpath(RZ_JOIN_2_PATHS(RZ_PREFIX, RZ_BINDIR));
	if (!bindir) {
		goto prefix;
	}
```

this does not work because RZ_PREFIX might refer to non-existing directories so realpath returns NULL and the whole thing fails. The PORTABLE code path should not use RZ_PREFIX directly.

**Comment by XVilka** [comment]
I believe, it was fixed, right? cc @wargio @ret2libc

**Comment by ret2libc** [comment]
I'd like to test following the reproduction steps above before the release before closing this.

**Comment by wargio** [comment]
this is fixed on all platforms.

**Comment by XVilka** [comment]
@ret2libc I am closing this, please reopen if it still happens.
