### ISSUE TITLE
The new cutter dev version unable to commit change

### ISSUE THREAD

**Issue by l12436** [rizinorg/cutter#2910]
**Environment information**
* Operating System: ubuntu 20.04
* Cutter version: dev version
* Obtained from:
  - Built from source
* File format: PE

**Describe the bug**
the new dev version of cutter is unable to save change in cache mode
the file permission is `-rwxrwxr-x`

**To Reproduce**

1. prepare a binary with write version or chmod 775
2. using cutter to open that binary
3. switch to cache mode
4. modify binary
5. commit change
6. you will see the change did not saved

**Expected behavior**

It should save change once I commit change

**Screenshots**

**Additional context**

**Comment by XVilka** [comment]
Cannot reproduce anymore. Don't forget to open file in the writeable mode in the opening dialog.
Let me know if it works for you, if it still doesn't - I will reopen the issue.
