### ISSUE TITLE
Navigation bar is empty

### ISSUE THREAD

**Issue by ITAYC0HEN** [rizinorg/cutter#2939]
**Environment information**
* Operating System: MacOS
* Cutter version: 2.0.5
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: Any

**Describe the bug**

The navigation bar at the top of the interface is empty

**To Reproduce**

1. Open any binary file in cutter
2. See that the navigation bar is empty. 

![image](https://user-images.githubusercontent.com/20182642/167283456-556a3514-5a07-4888-b8aa-5cc09268905a.png)

**Expected behavior**

It should contain the colorful markers of code and data

![image](https://user-images.githubusercontent.com/20182642/167283475-25ed33b3-46b0-488a-8f44-58b5792102e2.png)

**Comment by ITAYC0HEN** [comment]
@thestr4ng3r, is it solved now after https://github.com/rizinorg/cutter/pull/2953?

**Comment by thestr4ng3r** [comment]
It works for me at least. Can you retry with your setup and binary?

**Comment by XVilka** [comment]
@ITAYC0HEN I cannot reproduce on MacOS, please retest and close if fixed

**Comment by ITAYC0HEN** [comment]
Fixed :)
