### ISSUE TITLE
There is a problem with crowdin translation script.---AnalysisOptionsWidget.ui

### ISSUE THREAD

**Issue by fairycn** [rizinorg/cutter#2957]
Download crowdin's latest language file today to generate qm language pack. It is found that "AnalysisOptionsWidget.ui" has not changed, but the string has been translated. The name found by locating the relevant location code is different from the GitHub code, as follows:
cutter_zh.ts
![image](https://user-images.githubusercontent.com/74580422/171606541-ec790c19-385d-48c5-b21c-3672a8fc2cc6.png)
![image](https://user-images.githubusercontent.com/74580422/171607159-b2507bde-5655-4992-bb2b-38cb61913a6d.png)

![image](https://user-images.githubusercontent.com/74580422/171606984-d208471c-4464-49ec-bfe9-371289d945bb.png)

modify
![image](https://user-images.githubusercontent.com/74580422/171607536-20f717ea-def3-407e-a129-299d00b42ea2.png)
![image](https://user-images.githubusercontent.com/74580422/171608074-f4e7ab64-8a6d-430e-b664-a55cf51546c4.png)
Fix this error after modifying the code.

**Comment by thestr4ng3r** [comment]
Outdated strings were stripped from the files now.
