### ISSUE TITLE
Junk Instruction by changing Bytes

### ISSUE THREAD

**Issue by user18x** [rizinorg/cutter#2958]
If i change few bytes in a crackme the other bytes will be replaced with a junk instruction.

As example:
Let's say i change a 5 byte function (call...) to a 2 byte function (xor eax, eax) the last 3 bytes will be replaced with a junk instruction.
So i've to NOP this 3 bytes manually!

Why it couldn't be filled this 3 bytes with a NOP's?
Other debugger does this do!

**Comment by user18x** [comment]
Do you understand?
Will i get feedback?

**Comment by ret2libc** [comment]
Hi!

So, in Rizin there is the chance to use `wai <instruction>` to have the rest of the original instruction being replaced with nops, but I think this is not exported in Cutter.

It would probably be nice to have a checkbox in the "Edit -> Instruction" dialog window to say "fill rest of the instruction with nops", however this is not implemented yet. Moreover, that would only work for replacing one single instruction, but it would not if you want to overwrite multiple instructions.

As a workaround you can manually run the `wai` command from the rizin shell within Cutter, but AFAIK there is no direct way to do this through Cutter.
