### ISSUE TITLE
Crash while opening and parsing the file.

### ISSUE THREAD

**Issue by knifepjk** [rizinorg/cutter#2966]
**Environment information**
* Operating System: windows 10
* Cutter version: 2.0.5
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: 
 * Arch: N/A
 * Type: N/A

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by XVilka** [comment]
Not enough information to understand the problem.

**Comment by ITAYC0HEN** [comment]
Hey, we would love to fix the issue but sadly you didn't provide enough information so we can test and reproduce the bug.
Please submit more information, including the file that causes this issue (if possible).

Thank you! We'll close this issue for now but we'd love to re-open it once you update the description of the issue you're experiencing.
