### ISSUE TITLE
Invalid instructions near the end of the disassembly tab

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/cutter#2969]
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub: ./Cutter-git-2022-06-12-84b33d50bdd666825eada79a5fe0a2039bc2b1c6-x64.Linux.AppImage
  - [ ] Distribution repository
* File format: ELF x86_64

**Describe the bug**

Not enough bytes are disassembled in disassembly mode, causing "invalid" instructions to be decoded near the end of the linear disassembly.

**To Reproduce**

1. Open a binary
2. Go to the "Disassembly" mode.
3. Scroll until near the end of the disassembly window you don't start seeing "invalid" instructions. When scrolling back a bit, the invalid instructions will be correctly decoded, but when going back to the previous point they will still be displayed as "invalid"

**Expected behavior**

Cutter disassembles a bit more bytes than what it does now, so that it can correctly disassemble even longer instructions near the end of the "page".

**Screenshots**

![image](https://user-images.githubusercontent.com/562321/173761648-4821a7f9-d703-4799-9019-4202ad5029a6.png)
![image](https://user-images.githubusercontent.com/562321/173761683-cf772d46-0938-4a66-8654-ca8c1341f103.png)

**Additional context**

**Comment by karliss** [comment]
@ret2libc Can you still reproduce this? I don't see this anymore.  Recent cmd + json -> C api changes done by @imbillow might have affected how this works.

**Comment by ret2libc** [comment]
Will check later today.

**Comment by ret2libc** [comment]
I can't reproduce anymore.
