### ISSUE TITLE
Moving back and forth in the seek history does not correctly restore the right offset/relative position

### ISSUE THREAD

**Issue by ret2libc** [rizinorg/cutter#2970]
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub: ./Cutter-git-2022-06-12-84b33d50bdd666825eada79a5fe0a2039bc2b1c6-x64.Linux.AppImage
  - [ ] Distribution repository
* File format:

**Describe the bug**

When in disassembly mode and clicking on a flag in one of the "middle instructions", the seek is moved to the selected flag. However when you press ESC to go back to where you previously were, the seek is hard-moved to the instruction where the flag was used, instead of showing that instruction in the  middle of the screen like before.

**To Reproduce**

1. `./Cutter-git-2022-06-12-84b33d50bdd666825eada79a5fe0a2039bc2b1c6-x64.Linux.AppImage ./test/bins/elf/ls`
2. Go to "Disassembly" tab
3. Go to `main`
4. Double Click on `setlocale` (please note that the first instruction on the disassembly tab should be `push r15` and `call    qword [setlocale] ` should be somewhere behind)
5. Press ESC to go back to where you previously were
6. At this point you are back to the `call    qword [setlocale] ` instruction, but this instruction is now placed at the top of the Disassembly tab and not in the middle like it was before jumping to `setlocale`.

**Expected behavior**

The view goes back to exactly where it was before. This is consistent with Rizin and it is done also by IDA.

**Screenshots**

Initial position:
![image](https://user-images.githubusercontent.com/562321/173763684-755c8ef1-5114-4d09-9c7d-587e2aa387fe.png)

After going back with ESC:
![image](https://user-images.githubusercontent.com/562321/173763780-6d076836-292f-4d02-a4c7-6c1ef62f8b64.png)

**Additional context**

**Comment by whol-hoopa** [comment]
I will work on this

**Comment by whol-hoopa** [comment]
This is too hard for me so I won't work on this anymore.
