### ISSUE TITLE
X-Refs window is broken

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#3003]
**Environment information**
* Operating System: Arch Linux
* Cutter version:  db0d4d85a600eddec46f1ac3d9b98f133e187ee4 with latest dev rizin (d1c8bac7380cd065275a6a6ff92902ab69c1c3fb)
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF

**Describe the bug**

Disassembly preview in XRefs window show nonense, probably due to change in rizin command interface.

**To Reproduce**

* open executable in Cutter
* click on some function which is referenced by something
* open X-refs window

**Expected behavior**

Disassembly is visible

**Screenshots**

![image](https://user-images.githubusercontent.com/7101031/180849481-c9ecb356-f217-4ff9-bc39-16164dfb3715.png)

**Additional context**

Couldn't compile the Cutter with the version if rizin currently referenced by submodule (implicit strcmp usage in libzip or something like that). That seems to be fixed in latest rizin dev version.

**Comment by ret2libc** [comment]
I guess there was some command called there and probably it broke as we moved it to RzShell. We should use the API anyway, so the fix is probably to use the right API.

**Comment by XVilka** [comment]
Yes, see https://github.com/rizinorg/cutter/issues/2666 and https://github.com/rizinorg/cutter/pull/2996

**Comment by XVilka** [comment]
@imbillow assigning it to you since it fits the task of converting from commands to the API use, OK?

**Comment by karliss** [comment]
Already solved by #2996
