### ISSUE TITLE
Ability to define global variables

### ISSUE THREAD

**Issue by gsingh93** [rizinorg/cutter#3042]
In the disassembly view of a program,  I see instructions like `mov rax, qword [0x00005040]`, where `0x00005040` is a global variable in the .data segment. I couldn't find a way to actually create a global variable at that location though. In the same way we can define right click and define a function, we should be able to right click and define an address as data.

Ideally though, Cutter should be able to automatically define a variable here for me, as this is what Ghidra, IDA, and other programs do.

**Comment by XVilka** [comment]
Depends on:
- https://github.com/rizinorg/rizin/issues/1495
- https://github.com/rizinorg/rizin/issues/1437
