### ISSUE TITLE
Disassembly widget doesn't show reflines

### ISSUE THREAD

**Issue by XVilka** [rizinorg/cutter#3045]
**Environment information**
* Operating System: MacOS 12.6 ARM64 (M1)
* Cutter version: https://github.com/rizinorg/cutter/commit/8ad700a6dc1a4a628f23ebefa2138c5f8df0182d
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: any

**Describe the bug**

Compare Cutter output

<img width="1512" alt="Screen Shot 2022-10-08 at 13 06 24" src="https://user-images.githubusercontent.com/203261/194689694-6acf898f-2f6d-448e-b86d-909da47ad5e7.png">

And Rizin output

<img width="946" alt="Screen Shot 2022-10-08 at 13 09 19" src="https://user-images.githubusercontent.com/203261/194689726-0a2c7fbe-697e-4a02-8784-6d88911bdee9.png">

**To Reproduce**

1. Open any file, e.g. /bin/ls
2. Open with analysis `aaa`
3. Switch to disassembly widget
4. Open function with reflines (check in Rizin first)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wavexx** [comment]
I can confirm this on linux/debian too. This used to work, but at some point they just disappeared.
