### ISSUE TITLE
Publish a `winget` manifest.

### ISSUE THREAD

**Issue by bartoszek** [rizinorg/cutter#3056]
Since `choco` is getting shittier and outdated, and windows seems serious
about its own package downloader discased as package manager aka. `winget`
Could we pretty please have a `winget-pkg` manifest published for the `Cutter`.
It would greatly improve M$ user experience since `winget` doesn't requires
admin privileges to work and its pkg base is up to date'ier compared to `choco` now.
_btw. Tired contacting on your telegram channel, but its no more 😢

**Comment by wargio** [comment]
Hello @bartoszek when did you write on telegram? this is the first time hearing this and i check the chat daily. be sure to be in the right telegram chat: https://t.me/cutter_re

**Comment by bartoszek** [comment]
GitHub issue tracker points to the wrong one then, it says @r2cutter ¯⁠\\\⁠_⁠(⁠ツ⁠)\⁠_⁠/⁠¯

**Comment by wargio** [comment]
i have fixed the link. thanks for poiniting it out.

**Comment by XVilka** [comment]
See also https://github.com/rizinorg/ideas/issues/20

**Comment by assarbad** [comment]
Allegedly this seems to be technically possible now: https://github.com/microsoft/winget-cli/issues/140 (also see [this](https://devblogs.microsoft.com/commandline/windows-package-manager-1-4/))

**Comment by XVilka** [comment]
https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Rizin/Cutter
