### ISSUE TITLE
license

### ISSUE THREAD

**Issue by deepblueparticle** [rizinorg/cutter#3058]
**Environment information**
* Operating System: windows 10
* Cutter version: 2.1.2
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: 
 * Arch: N/A
 * Type: N/A

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by xarkes** [comment]
Hello, it looks like you published the default issue template. If you have an actual issue to report, feel free to edit and reopen this issue. Thanks!
