### ISSUE TITLE
Attaching problem at "CutterCore::attachDebug"

### ISSUE THREAD

**Issue by whol-hoopa** [rizinorg/cutter#3061]
**Environment information**
* Operating System: Windows 10
* Cutter version: 2.1.2 and commit "d58edca0c858e96fd75ae22627e86eaec09de588"
* Obtained from:
  - [ x] Built from source
  - [ x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**
attaching programs doesn't work
![image](https://user-images.githubusercontent.com/47489579/209611727-63cbbf38-a5ce-4952-9454-0a1a82f6274e.png)

**To Reproduce**

1. Go to "Debug" on toolbar
2. Click on "Attach to Process"
3. See error

**Expected behavior**
Expected to connect with debugger

**Screenshots**

**Additional context**
I found the problem at function "CutterCore::attachDebug(int pid)" in the file "Cutter.cpp"; compiled with commit "d58edca0c858e96fd75ae22627e86eaec09de588"
The release version(Cutter 2.1.2) doesn't have the problem.

**Working Code**
![image](https://user-images.githubusercontent.com/47489579/209612238-a2c77396-1996-449b-af70-7ebc3eb7a24f.png)

The commit version changed the "asyncCmd" part of the code. 
"asyncCmd" function got removed but idk if it got removed for some important reason(so i didn't use it)

![image](https://user-images.githubusercontent.com/47489579/209612426-9c38e04f-52e9-4394-b819-f7e4f5abc949.png)

I would like to learn how this problem would be fixed
My Guess - The Function at the end starts task that was supposed to be put in the beginning but the function doesn't have a task to do at the end so it crashes at "debugTask->startTask()".

**Making it Work**(copied some code from release)
![image](https://user-images.githubusercontent.com/47489579/209613602-1810a229-6eae-4443-811d-bd517050fb84.png)

**Comment by ITAYC0HEN** [comment]
CC @yossizap

**Comment by XVilka** [comment]
Looking at the code, I think the problem is in the `free(uri)`, actually. It is used as a pointer somewhere later in the code. Try to remove it and check again - I think it should fix the problem.

**Comment by XVilka** [comment]
I tried myself - removing `free(uri)` didn't help - the crash is still here.

**Comment by XVilka** [comment]
@whol-hoopa please try this PR: https://github.com/rizinorg/cutter/pull/3139

**Comment by whol-hoopa** [comment]
@XVilka 
The attach part seems fixed. 
After I attached to a program and press the continue button, it sends me to the starts of the entire program(to 0x000). 
I moved the cursor to some other function and pressed the continue button, but it also sent me to the start of the program.

The "start debug" from the debug menu works, when I do it the first time.
After I stop it and do the "start debug" again, it has the same behavior( sending me to the start of the program ).

I'm on Windows 10

Do you have this problem?
