### ISSUE TITLE
sample python plugin not refactored: fortune command

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#3075]
**Environment information**
* Operating System: linuxmint 20.3
* Cutter version: 2.1.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub (AppImage)
  - [ ] Distribution repository

**Describe the bug**

The sample python plugin does not work as expected, as the command `fo` for fortunes apparently has been replaced by the explicit `fortune` command.

**To Reproduce**

1. Download [sample_python.py](https://github.com/rizinorg/cutter/blob/dev/src/plugins/sample-python/sample_python.py)
2. Save it in the respective plugins directory
3. Open cutter
4. Click `Want a fortune?` in the `Sample Python Plugin` tab
5. No fortune is displayed / See error in console

**Expected behavior**

Fortune should be displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/19511852/211388758-a7f14345-03a5-428f-bb61-8f2be0d69072.png)

**Personal Opinion / Feedback**
I don't quite understand why `fo` won't be evaluated to `fortune`, as there is no other command starting with `fo`.
Also, I always expected commands to be nested strictly, meaning that any command starting with `f` will be listed under `f?` and will relate to what the `f…` commands are supposed to achieve (managing flags in this specific case).

I suppose, the special behavior of `fortune` (as well as `?E` for that matter) is a relic from radare and attempts to survive certain functionality in a quick'n'dirty fashion.

**Related Issues**
Minimal effort let me conclude, that the following issues might be related to this one:
#2666 
#3035

**Comment by XVilka** [comment]
> I don't quite understand why fo won't be evaluated to fortune, as there is no other command starting with fo.
Also, I always expected commands to be nested strictly, meaning that any command starting with f will be listed under f? and will relate to what the f… commands are supposed to achieve (managing flags in this specific case).
>
> I suppose, the special behavior of fortune (as well as ?E for that matter) is a relic from radare and attempts to survive certain functionality in a quick'n'dirty fashion.

No, various such commands listed in the `shell` category, which you can get help for with `shell?` command:
https://github.com/rizinorg/rizin/blob/dev/librz/core/cmd_descs/cmd_shell.yaml
