### ISSUE TITLE
Support graph and disassembly widgets scrolling with `<PgUp>`/`<PgDown>` 

### ISSUE THREAD

**Issue by XVilka** [rizinorg/cutter#3078]
**Is your feature request related to a problem? Please describe.**

Currently, the graph can't be scrolled with `<PgUp>`/`<PgDown>` (or `<Fn>+<UpArrow>`/`<Fn>+<DownArrow>` on my MacBook), it requires using mouse/trackpad.

**Describe the solution you'd like**

It's is intuitive to use `<PgUp>`/`<PgDown>` for scrolling in all widgets. For example, Binary Ninja does that.

**Comment by R-ohit-B-isht** [comment]
hello ,I'd like to work on this.

**Comment by XVilka** [comment]
@R-ohit-B-isht sure, go ahead

**Comment by R-ohit-B-isht** [comment]
@XVilka but we can sroll the graph with arrow keys so do we still need PgUp/PgDown for the same?

**Comment by XVilka** [comment]
Yes, but PgUp/PgDown should scroll more than arrows obviously.
