### ISSUE TITLE
PythonAPI.cpp#L35 / Reference counter increase required? / Py_INCREF(Py_None)

### ISSUE THREAD

**Issue by Semnodime** [rizinorg/cutter#3081]
Is this line of code 
https://github.com/rizinorg/cutter/blob/8cc4d14a6fe0b1a0ce6baf2a2f280342eed64e0c/src/common/PythonAPI.cpp#L35
missing a `Py_INCREF(Py_None);` as in
https://github.com/rizinorg/cutter/blob/8cc4d14a6fe0b1a0ce6baf2a2f280342eed64e0c/src/common/PythonAPI.cpp#L49
?

**If not**, could somebody **please explain for which reason the reference counter does not need to be increased** in L35, is it done automatically or not required?
Just stumbled upon this while trying to figure out how the python bindings are implemented.

**Comment by XVilka** [comment]
You are right, it should, there is even macro in newer Python versions called `Py_RETURN_NONE`: https://docs.python.org/3/c-api/none.html#c.Py_None
