### ISSUE TITLE
regression in dev-build? left gutter arrows lost in disasm panel

### ISSUE THREAD

**Issue by the-Arioch** [rizinorg/cutter#3091]
See #3090 for information

See the `0x77c5d45a    0f 85 7a ec ff ff    jne 0x77c5c0da`  opcode, and the left gutter of it

* In the released version there are arrows towards JNZ target far above and likes of it.
* But not any more in the mentioned there dev-build.

![2023-02-02 03_34_17-Cutter – WinTargets_xp_x64_user32 dll](https://user-images.githubusercontent.com/937774/216203250-ee3c926a-c74c-4c52-9b03-e57e4ec8e238.png)

![So it was](https://i.imgur.com/yzUSb8J.png)

**Comment by XVilka** [comment]
Duplicate of https://github.com/rizinorg/cutter/issues/3045

**Comment by the-Arioch** [comment]
Indeed, looks liek a DUP
