### ISSUE TITLE
Cutter Freezes When Loading Rust Binary

### ISSUE THREAD

**Issue by MCterra10** [rizinorg/cutter#3117]
**Environment information**
* Operating System: Arch Linux 6.1.9-zen
* Cutter version: cutter 2.1.2
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository
* File format: Rust binary from hackthebox `rauth: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=fc374b8206147fac9067599050989191b39eefcf, with debug_info, not stripped`

**Describe the bug**
Cutter hangs when loading the binary, even with all analysis options disabled. Binary is ~9MB.
![output](https://user-images.githubusercontent.com/11001588/218452498-1adb1195-cb3f-49ba-bf2b-6ec6a67c69ed.png)

**To Reproduce**
Load binary from hackthebox (I have not uploaded the binary to avoid issues with suspect phishing or malware). The link to the hackthebox challenge is here: https://app.hackthebox.com/challenges/231

Make sure all analysis options disabled and observe the freeze.

**Expected behavior**
Application does not freeze

**Comment by wargio** [comment]
[rauth.zip](https://github.com/rizinorg/cutter/files/10767068/rauth.zip)
