### ISSUE TITLE
Switch to Ubuntu 18.04 Docker **before** April 1st, 2023

### ISSUE THREAD

**Issue by XVilka** [rizinorg/cutter#3129]
> We have started the deprecation process for Ubuntu 18.04. While the image is being deprecated, You may experience longer queue times during peak usage hours. Deprecation will begin on 2022/08/08 and the image will be fully unsupported by 2023/04/01

https://github.com/actions/runner-images/issues/6002

**Comment by whol-hoopa** [comment]
There isn't a ubuntu 18.10 image. 
We can use ubuntu 20.04. 

https://github.com/actions/runner-images

**Comment by surendrajat** [comment]
It is currently blocked by https://github.com/probonopd/linuxdeployqt/issues/340 [check the logs [here](https://github.com/rizinorg/cutter/actions/runs/4566370376/jobs/8058775332?pr=3155)]
So we either wait for linuxdeployqt update or we move to https://github.com/linuxdeploy/linuxdeploy just like [wireshark did](https://github.com/wireshark/wireshark/commit/34ce99f32e3d478ebf2d4c9e24a10b3fe5ef4ef6).

**Comment by XVilka** [comment]
@Surendrajat looks like migration to `linuxdeploy` would be a better solution.

**Comment by wargio** [comment]
Requires a new version for
- https://github.com/rizinorg/cutter-deps
- https://github.com/rizinorg/cutter-deps-qt
