### ISSUE TITLE
C:\cutter\src\core/CutterDescriptions.h(358,30): error C3646: 'storageType': unknow n override specifier [C:\cutter\build\src\Cutter.vcxproj] C:\cutter\src\core/CutterDescriptions.h(358,41): error C4430: missing type specifie r - int assumed. Note: C++ does not support default-int [C:\cutter\build\src\Cutter .vcxproj]

### ISSUE THREAD

**Issue by whol-hoopa** [rizinorg/cutter#3136]
**Environment information**
* Operating System: Windows 10
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

I can't build cutter from source

**To Reproduce**

1. cd in cutter
2. cmake -B build
3. cmake --build build
4. errors 3646 and 4430
![image](https://user-images.githubusercontent.com/47489579/220461435-830464eb-b92e-42f7-9179-bb6eefce9a3e.png)

**Expected behavior**

Expected to build

**Additional context**

there is the type "RzAnalysisVarStorageType" but it seems like it is defined in a rizin header [librz/include/rz_analysis.h](https://github.com/rizinorg/rizin/blob/a3ef56347383f6aae587b8477adfc5ed4166039f/librz/include/rz_analysis.h)

#3062 is the issue it is that made this change not work for me (commit : d47eb1c41fed647e453f81aa6e38961440a61084)
the commit before that works for me (commit : d58edca0c858e96fd75ae22627e86eaec09de588)

**Comment by whol-hoopa** [comment]
#3062 is the issue it is that made this change not work for me (commit : d47eb1c41fed647e453f81aa6e38961440a61084)
the commit before that works for me (commit : d58edca0c858e96fd75ae22627e86eaec09de588)

**Comment by wargio** [comment]
did you use stable or dev ? also did you `git submodule update` before building ?

**Comment by whol-hoopa** [comment]
I used the branch "dev". I retried it with "git submodule update", it doesn't work and it still has the same errors.

I tried the "stable" branch and got 
cutter\src\core\Cutter.cpp(1849,22): error C2039: 'kind': is not a member of 'rz_analysis_var_t' 
cutter\src\core\Cutter.cpp(1850,14): error C2065: 'RZ_ANALYSIS_VAR_KIND_BPV': undeclared identifier 
cutter\src\core\Cutter.cpp(3106,19): error C3861: 'rz_analysis_var_count': identifier not found 
cutter\src\core\Cutter.cpp(4218,53): error C2065: 'RZ_GITTIP': undeclared identifier 
cutter\src\core\Cutter.cpp(4241,29): error C2065: 'rz_msg_digest_version': undeclared identifier
![image](https://user-images.githubusercontent.com/47489579/220528174-57d1ebc1-0493-4394-af9f-c0d21fef0831.png)

**Comment by XVilka** [comment]
Assuming you are trying Cutter from `dev` branch, try this:
```sh
git clean -xdff
cd rizin
git clean -xdff
git pull origin dev
```

**Comment by whol-hoopa** [comment]
I did this and it worked.  thanks
```git clean -xdff
cd rizin
git clean -xdff
git reset --hard origin/dev
cd ..
git checkout dev
git reset --hard origin/dev
cmake -B build
cmake --build build
