### ISSUE TITLE
[Hexagon] Assembly coloring and spaces are wrong

### ISSUE THREAD

**Issue by Rot127** [rizinorg/cutter#3138]
**Environment information**
* Operating System: Debian-11
* Cutter version: 2.1.2
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF

**Describe the bug**

The colors of the Hexagon assembly and spacing are wrong in Cutter.

The color issue possibly happens because the default tokenizer is used [here](https://github.com/rizinorg/rizin/blob/51e58685750a26678f8b1a1e68989fc25489c20c/librz/asm/asm.c#L1760) and for whatever reason not the tokens by the Hexagon plugin. Although, this is just a guess. But it would explain the weird colors. But it does not necessarily explain the difference in spacing.

The problem with the spacing could be related to this issue https://github.com/rizinorg/rizin/issues/2864. The differences in spaces was seen there as well.

**To Reproduce**

1. Open a Hexagon binary with Cutter (like `rizin-testbins/elf/analysis/hexagon-hello-loop`)
2. Click on `Disassembly`
3. See wrong colors and spacing

**Expected behavior**

Cutter assembly output should match Rizin's output. 

- Colors should follow the color pattern of Rizin.
- The assembly code should be properly aligned.

**Screenshots**

Cutter

![rz-1](https://user-images.githubusercontent.com/45763064/220476835-f8fa3b93-197b-4828-aedc-87f2f0de851e.png)

Rizin

![rz-2](https://user-images.githubusercontent.com/45763064/220476852-444a45dd-23dc-43ab-bf7e-49991fbf7a4b.png)

**Comment by XVilka** [comment]
@Rot127 please retry with the 2.2.0 release: https://github.com/rizinorg/cutter/releases/tag/v2.2.0

**Comment by Rot127** [comment]
Thanks for the reminder. It is fixed.
