### ISSUE TITLE
[Hexagon] Jump target arrows are incorrect

### ISSUE THREAD

**Issue by Rot127** [rizinorg/cutter#3141]
**Environment information**
* Operating System: Debian-11
* Cutter version: 2.2.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: ELF

**Describe the bug**

The arrows pointing to jump targets are incorrect. In the screenshots you can see that the arrow originating correctly from address `0x551c` in Rizin, starts incorrectly from address `0x5518` in Cutter.
The same problem happens with the addresses the arrow is pointing to.

**To Reproduce**

1. Open a Hexagon binary with Cutter like `rizin-testbins/elf/analysis/hexagon-hello-loop`
2. Go to `0x5500` or any other offset in the binary
3. Compare the arrows to Rizin
4. See mismatch

**Expected behavior**

The arrows pointing to the same offset as in Rizin.

**Screenshots**

Rizin

![rz-1](https://user-images.githubusercontent.com/45763064/220961311-a5dbe892-2658-4fe0-a7c6-82efa76f4550.png)

Cutter
![rz-2](https://user-images.githubusercontent.com/45763064/220961414-7a88a7f0-75cf-4beb-a621-886db1c07136.png)

**Additional context**

The bug possibly comes from the way the jump targets for Hexagon instructions are set.

Hexagon has very long instruction words. Those instruction words are commonly referred to as packets. Each packet can contain multiple instructions. Each packet has a single PC address associated to it. This PC address is always equal to the start of the packet (the first instruction in the packet).

PC-relative jump targets are always relative to the packet address. If a packet is not completely disassembled (the first instruction is unknown) the packet address is not known. Hence the jump target is incorrectly calculated from the wrong address.

The bug likely originates from this behavior. The arrows are possibly drawn when the packet is still not disassembled completely. Because of that the jump targets are calculated relative to the wrong address (not the first one in the packet). Due to that the arrows point to an incorrect jump target.

Contrary to Rizin, Cutter might not update it's GUI after each user interaction. So the incorrect arrows remain.

I haven't done any debugging, but it seems the most likely reason for this bug to me.

Relevant chapters in the [Hexagon programmers reference manual v67](https://developer.qualcomm.com/qfile/67417/80-n2040-45_b_qualcomm_hexagon_v67_programmer_reference_manual.pdf):
- Ch. 3.3.2 - Sequence semantics (Intro into packets + the PC of a packet is equal to the start of a packet)
- Ch. 8.3 - Software Branches (general info about branches).

**Comment by XVilka** [comment]
Probably same reason as in https://github.com/rizinorg/cutter/issues/3114

**Comment by karliss** [comment]
To me it looks more like mismatch between drawing and text row size. Possibly caused by font,  bad highdpi calculations or text field having additional scroll offset.

Arrows pointing between two lines of assembly is a giveaway for this. Even if Hexagon packet instructions caused bad address calculation arrow should still point to a middle of text line.

**Comment by XVilka** [comment]
I confirm, our reflines are heavily misaligned. Opened `/bin/ls` on macOS ARM64:

<img width="1512" alt="Screenshot 2023-05-13 at 12 39 49" src="https://github.com/rizinorg/cutter/assets/203261/272ba298-63a7-43d7-87f9-e757eefd0a63">

**Comment by XVilka** [comment]
See also https://github.com/rizinorg/cutter/issues/2615
