### ISSUE TITLE
Crashes when decompiling certain file with rz-ghidra

### ISSUE THREAD

**Issue by zhufengning** [rizinorg/cutter#3145]
**Environment information**
* Operating System: x86_64 Manjaro Linux
* Cutter version: 2.1.2
* Obtained from:
  -  Distribution repository 
* File format:
ELF64
    Library: GLIBC(2.2.5)[DYN AMD64-64]
    Compiler: gcc((Debian 9.3.0-11) 9.3.0)[DYN AMD64-64]
**Describe the bug**
  Open the main function, and switch to the Decompiler tab. And then terminated by signal SIGABRT (Abort).
[the_file.zip](https://github.com/rizinorg/cutter/files/10871857/a.zip)

**Comment by XVilka** [comment]
Please retry with the latest release since 2.1.2 is outdated: https://github.com/rizinorg/cutter/releases/tag/v2.2.0

**Comment by zhufengning** [comment]
> Please retry with the latest release since 2.1.2 is outdated: https://github.com/rizinorg/cutter/releases/tag/v2.2.0

Thanks, it works.
