### ISSUE TITLE
Console does ignore tab characters at the beginning of a line

### ISSUE THREAD

**Issue by lukasfink1** [rizinorg/cutter#3193]
**Environment information**
* Operating System: Arch Linux
* Cutter version: Tested on both 2.2.1-makepkg-f4be9a8 and 2.2.0-dev-4491760
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

When receiving tab characters (`'\t'`) at the beginning of a line, the Console does not indent the line.

**To Reproduce**

Open Console (Windows->Console or Ctrl+`)
Type:
```sh
> !printf 'Hello World\n' # This is ok.
Hello World
> !printf '\tHello World\n' # Here should be some indentation (traditionally 8 characters)
Hello World
> !printf '  Hello World\n' # Spaces work
  Hello World
> tc timeval # This is where rizin uses tabs for indentation
struct timeval {
time_t tv_sec;
suseconds_t tv_usec;
};
```

**Expected behavior**

I expected the following output:
```sh
> !printf 'Hello World\n' # This is ok.
Hello World
> !printf '\tHello World\n' # Here should be some indentation (traditionally 8 characters)
        Hello World
> !printf '  Hello World\n' # Spaces work
  Hello World
> tc timeval # This is where rizin uses tabs for indentation
struct timeval {
        time_t tv_sec;
        suseconds_t tv_usec;
};
```

**Screenshots**
![screenshot](https://github.com/rizinorg/cutter/assets/3033969/22bb7c4b-1c21-4058-b315-9c86309db0c6)

**Comment by ret2libc** [comment]
Seems to work in Rizin, thus it's likely a Cutter-specific bug.

**Comment by beauby** [comment]
Likely culprit is this [`appendHtml()`](https://github.com/rizinorg/cutter/blob/dev/src/widgets/ConsoleWidget.cpp#L235) which should probably be an `appendPlainText()`.

**Comment by lionkor** [comment]
I'll give this one a try.

appendPlainText sadly doesn't work as it would render what rizin outputs as non-breaking-spaces as `&nbsp;`, and similar
