### ISSUE TITLE
Cutter 2.3.0 cannot work on MacOS 12.x (Monterey)

### ISSUE THREAD

**Issue by gingerbeardman** [rizinorg/cutter#3226]
**Environment information**
* Operating System: macOS 12.6.8
* Cutter version: 2.3.0
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: arm64 dmg

**Describe the bug**

- Cutter 2.3.0 requires macOS 13+

**Additional context**

- 2.3.0 will work if I open the binary inside the package `/Applications/Cutter.app/Contents/MacOS/cutter`
- 2.2.1 works OK as a normal app
- Similar older issue: https://github.com/rizinorg/cutter/issues/2648

**Comment by ret2libc** [comment]
@gingerbeardman does it work on v2.3.2?

I'm on Cutter 2.3.2/rizin 0.6.2, just downloaded from the release page and I'm on macOS Monterey 12.7. It works for me.

Btw, are you sure you need the *arm64* dmg and not the *x86_64* dmg?

**Comment by XVilka** [comment]
@ret2libc are you still on Monterey? Could you please try the latest `dev` build? https://github.com/rizinorg/cutter/actions/runs/7992706709

**Comment by gingerbeardman** [comment]
@ret2libc I ended up moving to Sonoma, Jan 2024.

**Comment by ret2libc** [comment]
> @ret2libc are you still on Monterey? Could you please try the latest `dev` build? https://github.com/rizinorg/cutter/actions/runs/7992706709

I should have a laptop on Monterey, I can test it

**Comment by ret2libc** [comment]
Works for me. But, reading my previous comment, it was already working... I guess we can close this for now and re-open if more details come.
