### ISSUE TITLE
Selecting "enter port" box in remote debug causes freeze

### ISSUE THREAD

**Issue by duckcantcode** [rizinorg/cutter#3276]
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: none

**Describe the bug**

Right clicking inside the "enter port" box in remote debug causes the entire program to freeze

**To Reproduce**

1. Open Cutter
2. Select "Don't open any file"
3. Hit Open
4. Go to debug -> remote debugger
5. Click ok
6. Select the enter port box
7. Right click

**Expected behavior**

Some sort of "Select All, Copy, Paste" menu

**Screenshots**

None

**Additional context**

None

**Comment by lorsanta** [comment]
This is fixed now, I tested it with version 2.3.4
