### ISSUE TITLE
Untranslated string in settings

### ISSUE THREAD

**Issue by GermanAizek** [rizinorg/cutter#3287]
This line is never translated https://github.com/rizinorg/cutter/blob/e3087e727af1c4b1362407476faeda6a3d2c2e08/src/tools/basefind/BaseFindDialog.cpp#L19

I noticed an error from another issue here: https://github.com/rizinorg/cutter/issues/3286

**Comment by XVilka** [comment]
Duplicate of https://github.com/rizinorg/cutter/issues/3187

Please send a PR, just add a `tr()` macro.
