### ISSUE TITLE
Cutter quit unexpectedly

### ISSUE THREAD

**Issue by b1llow** [rizinorg/cutter#3305]
**Environment information**
* Operating System: macOS 14.3.1
* Cutter version: 2.3.3
* Obtained from:
  - [ ] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository
* File format:

**Describe the bug**

Cutter quit unexpectedly when open graph view with the function `bins/v850/hello-v850e:dbg._vfprintf_r`.

The function has 300+ blocks, maybe that's the main reason? In rizin it shows up quickly on the console, but the whole graph is quite confusing.

**To Reproduce**

1. Open `bins/v850/hello-v850e`
2. Choose the graph view
3. Choose the function `dbg._vfprintf_r`

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by karliss** [comment]
Couldn't repeat on Linux using devbuild, didn't yet test what happens with 1.3.3 .

300+ blocks shouldn't be an issue, it's not little but it's also not that much .

@imbillow Can you clarify what from where you downloaded Cutter? Only thing you could consider first party software  repository on macOS is AppsStore but the Cutter shouldn't be available there. As for third party package managers on macOS there are many of them.

**Comment by karliss** [comment]
Not sure if it's related but after trying out few things did get a crash when right clicking in the graph view. In almost any executable/function. Will investigate that further tomorrow.

The recent  changes to getRzAnalysisBytesSingle look incorrect.

**Comment by XVilka** [comment]
@imbillow could you please check if it happens on the current `dev` of Cutter?

**Comment by XVilka** [comment]
I retried with exact same OS the build from `dev` - it doesn't happen anymore.

**Comment by XVilka** [comment]
Closing this as it was (apparently) fixed.
