### ISSUE TITLE
Cutter-v2.3.3-Linux-x86_64.AppImage crashed

### ISSUE THREAD

**Issue by qux-bbb** [rizinorg/cutter#3306]
**Environment information**
* Operating System: Ubuntu 23.04
* Cutter version: v2.3.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub
  - [ ] Distribution repository
* File format: elf

**Describe the bug**

Right click in the disassembly interface will exit directly.

**To Reproduce**

1. Go to 'disassembly interface'
2. Right click on any instruction
3. See error

**Expected behavior**

It should show a menu.

**Additional context**

The log:
```
./Cutter-v2.3.3-Linux-x86_64.AppImage 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
"0.7.0" "0.7.0"
Setting PYTHONHOME = "/tmp/.mount_CutterG3OP7T/usr"  for AppImage.
PYTHONHOME = "/tmp/.mount_CutterG3OP7T/usr"
ERROR: rz_sys_dlopen: error: /tmp/.mount_CutterG3OP7T/usr/lib/rizin/plugins/librz_yara.so (libcrypto.so.1.1: cannot open shared object file: No such file or directory)
Plugins are loaded from "/home/alice/.local/share/rizin/cutter/plugins"
Native plugins are loaded from "/home/alice/.local/share/rizin/cutter/plugins/native"
Python plugins are loaded from "/home/alice/.local/share/rizin/cutter/plugins/python"
Loaded 0 plugin(s).
Plugins are loaded from "/tmp/.mount_CutterG3OP7T/usr/share/ubuntu/rizin/cutter/plugins"
Plugins are loaded from "/tmp/.mount_CutterG3OP7T/usr/share/gnome/rizin/cutter/plugins"
Plugins are loaded from "/tmp/.mount_CutterG3OP7T/usr/local/share/rizin/cutter/plugins"
Plugins are loaded from "/tmp/.mount_CutterG3OP7T/usr/share/rizin/cutter/plugins"
Native plugins are loaded from "/tmp/.mount_CutterG3OP7T/usr/share/rizin/cutter/plugins/native"
Load Error for plugin "libcutter_yara_plugin.so" : "Cannot load library /tmp/.mount_CutterG3OP7T/usr/share/rizin/cutter/plugins/native/libcutter_yara_plugin.so: (librz_yara.so: cannot open shared object file: No such file or directory)"
Loaded 1 plugin(s).
Plugins are loaded from "/var/lib/snapd/desktop/rizin/cutter/plugins"
Segmentation fault (core dumped)
```

**Comment by XVilka** [comment]
Could you please provide a stacktrace? I think it might be the same issue as https://github.com/rizinorg/cutter/issues/3305

**Comment by qux-bbb** [comment]
> Could you please provide a stacktrace? I think it might be the same issue as #3305

How can I get a stacktrace?

**Comment by qux-bbb** [comment]
Maybe it relates to https://github.com/rizinorg/cutter/pull/3308, but I don't know.

**Comment by karliss** [comment]
Yes, if the crash happens after right clicking it's probably the same issue as #3308 .

You can try the CI build from pull request here https://github.com/rizinorg/cutter/actions/runs/8056481691

**Comment by qux-bbb** [comment]
The CI build works. Thank you!

**Comment by djwesty** [comment]
I am experiencing the same issue with the 2.3.3 x86-64 app image on ubuntu 20.04

**Comment by karliss** [comment]
@djwesty 

That's to be expected if you are still using the same old buggy version you will get the same old bugs. So unless you are using a dev build you will have to wait until next patch release to get a version with the fix. 

I hope this won't discourage you from making comments in future, just a little advice for doing it even better helping keepi issue tracker organized.

In general "same here" type comments for an issue are useful only in few situations:
* if they provide some new additional information
* issue is in early unconfirmed state, it's unclear what platforms or versions are affected or attempts to reproduce it have been successful

Once the issues has been reproduced by developers or even patched (as can be seen in comments above) telling that the old unpatched version still has the bug on roughly the same OS as other reports isn't useful anymore, unless you were testing and able to repeat the bug with patched version meaning that fix is incomplete.

If you are affected by issue but don't have any new information to add please use the reaction button and thumbs up the issue. It is still useful to gauge  how many people are affected by the problem and choosing how to prioritize them. 
![image](https://github.com/rizinorg/cutter/assets/7101031/efe25af4-d749-4264-b5a1-2ee8c8dab645)

**Comment by djwesty** [comment]
Understood, thanks for explaining. 

At first glance it seemed like this issue was closed without redress but now I see it's solved in the upcoming patch

Thanks for the hard work
