### ISSUE TITLE
freezes on MacOS apple silicon

### ISSUE THREAD

**Issue by XFajk** [rizinorg/cutter#3307]
**Environment information**
* Operating System: MacOS apple silicon
* Cutter version: 2.3.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository

**Describe the bug**
the bug just freezes the app when I try to disassemble an executable it freezes at this point 
<img width="405" alt="Screenshot 2024-02-26 at 02 46 33" src="https://github.com/rizinorg/cutter/assets/89221002/48550c8c-ef18-416f-bb0d-a99011dec0d9">
this bug wasn't happening in 2.3.2
I tried to open a simpler executable than one that opened the editor window but it also froze after that 

**To Reproduce**

1. open the app and select an executable file 
the file that opened the editor and froze was compiled from this C code 
```C
#include <stdio.h>

int main() {
	int x = 1337;
	while(x--) {
		printf("ayo\n");
	}

	return 0;
}
```
2. when you choose the file select the default options for analysis aka auto and "Use virtual addressing", "import detangled symbols" (also the write mode option has no effect I tried it with it on and off)
3. Press OK and it should freeze
**Expected behavior**

I expected it to work and give me the functionality of the app like the disassembler (not much to say here)

**Additional context**

I am an absolute beginner in reverse engineering so any question to get more context that will need more knowledge about reverse engineering are impossible for me to answer

**Comment by XFajk** [comment]
A new discovery tried to build it from the source(specifically from the dev branch) and this version works so this is probably a problem with the release version

**Comment by ret2libc** [comment]
Doesn't happen to me on Apple M1. Did you install any rizin/cutter plugin in the past?

**Comment by XFajk** [comment]
> Doesn't happen to me on Apple M1. Did you install any rizin/cutter plugin in the past?

No, I don't think so but I don't know where to check since the editor freezes on me where can I delete them or something 
or maybe even better where can I delete the data about cutter so it is like I am using cutter for the first time maybe that could help

**Comment by XVilka** [comment]
Could you please retry with the 2.3.4 release?
 https://github.com/rizinorg/cutter/releases/tag/v2.3.4

**Comment by XFajk** [comment]
> Could you please retry with the 2.3.4 release? https://github.com/rizinorg/cutter/releases/tag/v2.3.4

yeah this one works sorry for a late reply but I switched to ghidra in the mean time but now I can get on to cutter as I wanted originally
