### ISSUE TITLE
Program Unstable & Crashing

### ISSUE THREAD

**Issue by gluecia** [rizinorg/cutter#3310]
**Environment information**
* Operating System: Windows 11 Home 23H2
* Cutter version: v2.3.3
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:
PE32

**Describe the bug**
After updating, Cutter has become very unstable for me, crashing randomly and without warning, and this only happened after I updated to version 2.3.3, and is especially prone to crashes when switching between different decompiled functions.

**To Reproduce**

1. Open Cutter (project or not, the issue occurs regardless).
2. Navigate around (the crashes seem to happen when switching tabs, especially between functions).
3. After a bit, it should crash.

**Expected behavior**
not crashing? i guess this field isnt too applicable here

**Screenshots**
N/A

**Additional context**
This issue only started occurring after updating to v2.3.3, and I've tried reinstalling v2.3.3 and switching back to v2.3.2, and when I switched back to the older version, the issue went away, so I wouldn't be surprised if the issue was to do with Rizin v0.7.0, but I'm not too sure. I didn't see any sort of log or crash file, but if Cutter produces those, I would be happy to upload it for further information!

**Comment by XVilka** [comment]
Yes, I think it's the same bug that was fixed in Rizin 0.7.1 and Cutter 2.3.4 (rc1 for now, will do a release later today). You can use this build: https://github.com/rizinorg/cutter/releases/tag/v2.3.4-rc1

**Comment by XVilka** [comment]
Should be fixed in https://github.com/rizinorg/cutter/releases/tag/v2.3.4

**Comment by gluecia** [comment]
oh thank you so much!! i didn't see that release, i just installed the version 2.3.2 told me to install, but it works now! thank you!
