### ISSUE TITLE
[Miscellaneous] Auto publish releases to Winget

### ISSUE THREAD

**Issue by Dragon1573** [rizinorg/cutter#3315]
## Is this feature request related to a problem?

NO. This feature is not for `cutter` executables.

Currently, this application is submitted to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) as `Rizin.Cutter` by contributors or volunteers. The manifest is manually updated at the moment, so some of the users complaining about the outdated manifests.

The moderators of [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) recommend authors or publishers automate their submit process, so a newer manifests can immediately noticed and submitted to the repository once the package is released.

## Targets we want to achieve

Configure a GitHub Workflow, automatically invoked when new release of this repository was published. The Workflow can create manifests of the new release and submit to [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs).

## Alternatives

Nope. I would prefer the above sulution.

## Additional context

- Related https://github.com/rizinorg/cutter/issues/3056
- See https://github.com/microsoft/winget-pkgs/issues/142824#issuecomment-1984772380
- There are [example configurations](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml) by Microsoft PowerToys

**Comment by karliss** [comment]
> The moderators of [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) recommend authors or publishers automate their submit process,

Sounds reasonable, do you have any links to docs or discussions with winget-pkgs moderators mentioning that this is the the recommended way for maintaining  winget manifests?

**Comment by Dragon1573** [comment]
Sorry, it's my fault. 😥 I can't find such kinds of documentations or discussions posted by Microsoft.

But I found several manifests (such as Oh My Posh) are directly maintained by the package author. They use GitHub Actions like [WinGet Releaser](https://github.com/marketplace/actions/winget-releaser), or implement the automation using shell scripts with [`YamlCreate.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md), [`wingetcreate.exe`](https://github.com/microsoft/winget-create) or [`komac.exe`](https://github.com/russellbanks/Komac). Most of their pull requests can be merged no more than 24 hours. 

For manual maintainence, this may take much longer. Community contributors and volunteers might not notice about the new release. The manifest will keep outdated until somebody open an issue complaining about it, and other create a pull request for manually update it.

@denelon Sorry to ping you here. Is there any official guide for package authors and publishers, which help them automate the manifest maintainence?
