### ISSUE TITLE
Can't Open Cutter: error while loading shared libraries: librz_core.so.0.5: cannot open shared object file.

### ISSUE THREAD

**Issue by rvyhvn** [rizinorg/cutter#3320]
**Environment information**
* Operating System: Debian Testing
* Cutter version: cutter-re 2.2.0-1 amd64
* Obtained from:
  - [] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [x] Distribution repository

**Describe the bug**

When opening cutter via desktop application, it won't open. I'm using KDE in Debian Testing. If I try to open via terminal with `cutter-re`, it shows:
```
cutter-re: error while loading shared libraries: librz_core.so.0.5: cannot open shared object file: No such file or directory
```

**To Reproduce**
1. Open the software from desktop application or via terminal using `cutter-re`

**Expected behavior**
The software run well.

**Comment by karliss** [comment]
That sounds more like an issue with packaging on Debian testing.  I don't think any of of debian package maintainers are here.

**Comment by rvyhvn** [comment]
> That sounds more like an issue with packaging on Debian testing. I don't think any of of debian package maintainers are here.

I guess I'll just build it myself then. Thanks
