### ISSUE TITLE
rizin/meson.build config still points to archived liblzma (xz-utils) repository.

### ISSUE THREAD

**Issue by buffermet** [rizinorg/cutter#3326]
**Environment information**
* Operating System: GNU/Linux
* Cutter version: Latest (https://github.com/rizinorg/cutter/commit/f8c7df8260bea74dabe45a7b961da339c277bd38)
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format: /

**Describe the bug**

Building from source is interrupted due to the recently archived liblzma (aka xz-utils) GitHub repository. (https://github.com/tukaani-project/xz/releases/download/v5.4.3/xz-5.4.3.tar.gz)

**To Reproduce**

Assuming all dependencies are installed.

```sh
git clone https://github.com/rizinorg/cutter
cd cutter/build
cmake ..
cmake --build .
```

**Expected behavior**

Installation succeeds.

**Screenshots**

n/a

**Additional context**

Building fails with the following hash mismatch error:

```
Dependency liblzma skipped: feature use_sys_lzma disabled
Downloading liblzma source from https://github.com/tukaani-project/xz/releases/download/v5.4.3/xz-5.4.3.tar.gz
A fallback URL could be specified using source_fallback_url key in the wrap file

../../../../rizin/meson.build:591:19: ERROR: Incorrect hash for source:
 1c382e0bc2e4e0af58398a903dd62fff7e510171d2de47a1ebe06d1528e9b7e9 expected
 b58ed9808431acd5d947f8499bfbb6fe9d05ec8a0d28ebbb477c9b4ad0ca6410 actual.
```

meson.build:591: https://github.com/rizinorg/rizin/blob/dev/meson.build#L591

I can see in the above logs that the dependency is automatically skipped, yet it still produces an error.

**Comment by XVilka** [comment]
It's fixed in the latest Rizin `dev`, should be easily fixable by updating the submodule.
