### ISSUE TITLE
can‘t modify the Language option

### ISSUE THREAD

**Issue by EGQM** [rizinorg/cutter#3331]
**Environment information**
* Operating System:ubuntu23.10
* Cutter version:2.4.0-dev-5750139
* Obtained from:
  - [x] Built from source
  - [ ] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository

**Describe the bug**

When compiling Cutter with default settings in Ubuntu 23.10 and executing ./cutter, I am unable to modify the Language option in Preferences - Appearance (there is only one option available, which is English).

**Comment by ITAYC0HEN** [comment]
Thanks for reaching out @EGQM :)
How did you build Cutter exactly?

Translations are included as a submodule:
https://github.com/rizinorg/cutter/blob/575013904100efdc71cbb9b614e4a1587f94ac7e/.gitmodules#L4-L6

Included in CMakeLists:
https://github.com/rizinorg/cutter/blob/575013904100efdc71cbb9b614e4a1587f94ac7e/src/CMakeLists.txt#L586

And  handled in `Translations.cmake`
https://github.com/rizinorg/cutter/blob/575013904100efdc71cbb9b614e4a1587f94ac7e/cmake/Translations.cmake

**Comment by EGQM** [comment]
@ITAYC0HEN  thank you for your help.
I compiled Cutter in the following way:
```
sudo apt install build-essential cmake meson libzip-dev zlib1g-dev qtbase5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools 
git clone --recurse-submodules https://github.com/rizinorg/cutter --depth=1
cd  cutter
mkdir build && cd build
cmake ..
cmake --build .
```

**Comment by EGQM** [comment]
The .qm files exist in ./build/src/translations, but after I run cutter, I can‘t modify the Language option.

**Comment by karliss** [comment]
It's probably because you didn't perform the install step. For everything to work properly files need to be placed in appropriate folder structure that's what the install step does.
 
If you directly run the compiled binary it's good enough for most development  work. But for some specific features or if you actually want to use the build long term, it might be necessarily to do the installation step .

**Comment by EGQM** [comment]
@karliss thank you very much.
After installation，it works.
