### ISSUE TITLE
Missing 4 file .DLL

### ISSUE THREAD

**Issue by tdeit** [rizinorg/cutter#3355]
![image](https://github.com/rizinorg/cutter/assets/139480830/70bd10f0-90eb-43b0-8485-27cff53021b8)
I have re-downloaded many old and new versions but this problem still appears. I don't know what to do, please help me

**Comment by karliss** [comment]
You need to have an appropriate version of VC runtime installed. If you don't have it already, there should be an installer in cutter folder 
![image](https://github.com/rizinorg/cutter/assets/7101031/c705321a-632c-4571-9bb4-4fa4c28e176d)

**Comment by tdeit** [comment]
> You need to have an appropriate version of VC runtime installed. If you don't have it already, there should be an installer in cutter folder ![image](https://private-user-images.githubusercontent.com/7101031/340457608-c705321a-632c-4571-9bb4-4fa4c28e176d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MTI0NzgsIm5iZiI6MTcxODcxMjE3OCwicGF0aCI6Ii83MTAxMDMxLzM0MDQ1NzYwOC1jNzA1MzIxYS02MzJjLTQ1NzEtOWJiNC00ZmE0YzI4ZTE3NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MThUMTIwMjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhhMjdkODZkY2JlZGE2NzUzZDlhZWM1M2M0MDZjM2FiZGViYzk1YjMwN2I2OGZiYTNiMTRjNWFlNDdhNTZiYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pxPT-sEriH6JkUOXPw2VjYZLkX9V5Avq1jDtQCcQQuQ)

thanks you, it works
