### ISSUE TITLE
Cutter Unable to load function name from a static, non-striped library

### ISSUE THREAD

**Issue by Chapoly1305** [rizinorg/cutter#3362]
**Environment information**
* Operating System:Ubuntu 22.04 x64
* Cutter version:Cutter-v2.3.4-Linux-x86_64.AppImage
* Obtained from:
  - [x] Downloaded release from Cutter website or GitHub 
* File format: libbotan-3.a

**Describe the bug**
The compiled .a file is statically linked and non-strip for extracting signatures purpose. The file can be load into Cutter, however the function names are not displayed. 

**To Reproduce**
1. Compile the libbotan 
```
wget https://botan.randombit.net/releases/Botan-3.5.0.tar.xz
tar xf Botan-3.5.0.tar.xz
cd Botan-3.5.0
./configure.py --disable-shared --cpu=x86_64 --os=linux --cc=gcc --with-endian=little --with-os-features=posix1 --with-debug-info --prefix=/path/to/botan/installation
make -j$(nproc)
```
2. Open the .a file with Cutter. 

**Expected behavior**
The names are needed to extract the signature. 
The Ghidra is able extract the .o from it and get the function names from the .a file, so it's expected to see the Cutter works the same. 
**Screenshots**

![image](https://github.com/rizinorg/cutter/assets/25316415/62680cc7-79f0-482d-a9f1-952b7b2601d0)

**Comment by wargio** [comment]
I belive this is an user error issue and the issue also resides how the rizin framework opens this.

Be aware that you will also find a very old known bug where you cannot open multiple files properly.

**That said, i strongly think that you did not open this using the `ar://` uri.**

In rizin & cutter you can open ar files (`.a` and `.la`) by appending `ar://` and the path. once you do this it, it will open it properly.
The next thing you will notice is that bug i just mentioned where you cannot select which file to view. to fix this issue what you can do is list before-hand what you want to open and open it by copying it as a "path". let me give you an example:

```bash
# open the archive
$ rizin ar:///lib/libz.a
# list the embedded files
[0x08000040]> ol
 3 * r-x 0x00000c08 ar:///lib/libz.a//adler32.o
 4 - r-x 0x000034c0 ar:///lib/libz.a//crc32.o
 5 - r-x 0x00005688 ar:///lib/libz.a//deflate.o
 6 - r-x 0x00002e20 ar:///lib/libz.a//infback.o
 7 - r-x 0x00000c00 ar:///lib/libz.a//inffast.o
 8 - r-x 0x00005318 ar:///lib/libz.a//inflate.o
 9 - r-x 0x00000e00 ar:///lib/libz.a//inftrees.o
10 - r-x 0x000038d8 ar:///lib/libz.a//trees.o
11 - r-x 0x00000ab0 ar:///lib/libz.a//zutil.o
12 - r-x 0x000008f0 ar:///lib/libz.a//compress.o
13 - r-x 0x000009b0 ar:///lib/libz.a//uncompr.o
14 - r-x 0x000005c8 ar:///lib/libz.a//gzclose.o
15 - r-x 0x000024d0 ar:///lib/libz.a//gzlib.o
16 - r-x 0x000021f8 ar:///lib/libz.a//gzread.o
17 - r-x 0x00001eb0 ar:///lib/libz.a//gzwrite.o
[...]
# close rizin
[0x08000040]> q
# open the desired file within the library.
$ rizin ar:///lib/libz.a//adler32.o
# check the symbols.
[0x08000040]> is
nth paddr      vaddr      bind   type size lib name              
-----------------------------------------------------------------
1   0x00000040 0x08000040 LOCAL  SECT 0        .text
2   0x00000040 0x08000040 GLOBAL FUNC 1120     adler32_z
3   0x000004a0 0x080004a0 GLOBAL FUNC 11       adler32
4   0x000004b0 0x080004b0 GLOBAL FUNC 224      adler32_combine
5   0x00000590 0x08000590 GLOBAL FUNC 224      adler32_combine64
```

* You can do the same in cutter, but it is easier if you pass the filename from the command line.

```bash
/tmp/Cutter-v2.3.4-Linux-x86_64.AppImage ar:///lib/libz.a//adler32.o
```

* Or from the UI:

![image](https://github.com/user-attachments/assets/a4a6244b-b9c8-4b98-bfa5-adc8cea4ea70)

**Comment by Chapoly1305** [comment]
Hi @wargio, thanks for the reply. I initially used file:// as you guessed. I tried your suggestion and prepend ar://, but it seems changes nothing, the functions are still not recongized. Please see the screenshot. 

![image](https://github.com/user-attachments/assets/70dd0655-43ef-4b68-a283-54427640d7bb)

The method to firstly list the contents of .a and load the .o to Cutter works as expected. 
![image](https://github.com/user-attachments/assets/313d01e1-b639-4798-8617-52c3703f5f42)

I am not sure if this is how it designed and the only way. There are way too many files for extracting signatures, is there a way to automate this? 

Thanks again!

**Comment by wargio** [comment]
the reason is that the bug i mentioned above will trigger and things will fuck up if you load only `ar://file.a`.
It is related to these bugs:
- https://github.com/rizinorg/rizin/issues/2588
- https://github.com/rizinorg/rizin/issues/2609
- https://github.com/rizinorg/rizin/issues/2685

These even if affecting another format, are the same bug. the issue is in the RzCore itself and requires a huge refactoring to just fix this. There are many dependencies that will need to be fixed before this will be handled properly.

As workaround use the strategy i showed you before where you list the files of the archive and open them like that or use `ar x file.a` to unpack it.

**Comment by wargio** [comment]
if you are creating signatures, do this as i do:
```
cd folder
ar x file.a
ls *.o | xargs -I % rz-sign -o '%.pat' '%'
```
then you will have a bunch of **pat** files that you can convert using the utilities mentioned in the book to merge them into one signature file.

you can also just unpack using `ar x file.a` and then use `generate-pat-from-obj.py` to generate the pat.

https://book.rizin.re/src/analysis/signatures.html#signature-database-creation

**Comment by Chapoly1305** [comment]
Very helpful and worked!
