### ISSUE TITLE
Nicer displaying of 1 instruction loops

### ISSUE THREAD

**Issue by karliss** [rizinorg/cutter#3369]
**Is your feature request related to a problem? Please describe.**

When displaying jump lines (or whatever the name for lines to the left of disassembly are called) for instructions that jump to themselves (infinite loop). 

![image](https://github.com/user-attachments/assets/32949c6d-55e7-416a-8c9f-5247a5f677d7)

I initially thought the line drawing code has bugged out. Took me a couple of seconds to read the disassembly until I realized what's going on.

**Describe the solution you'd like**

Add special case in the drawing code when instruction jumps to itself, maybe draw a loop arrow icon similar to 
![image](https://github.com/user-attachments/assets/3c5757db-2594-4e3a-84b5-bd4f2761fafa)

As a side effect it would also help more easily identify such single instruction infinite loops. For me that doesn't seem too important since normal code would rarely contain such (possibly infinite) loops although it shouldn't hurt either.  I have mostly seen them in interrupt vector handlers on embedded software. There might be cases on some architectures where you can make more meaningful loops out of single instruction, but nothing comes to my mind right now.   My primary motivation is to avoid drawing something that looks like drawing code is broken.

**Describe alternatives you've considered**

Slightly offset start end/of such arrows resulting in something like:
![image](https://github.com/user-attachments/assets/0c53a715-aee9-4ea0-b708-6b075832f121)
 Didn't we have something like that before? I though I have seen it , but I might be remembering it wrong. Or maybe those were jumps 1 instruction forward/back.

**Additional context**

**Comment by Rohan-here** [comment]
can i work on this?

**Comment by wargio** [comment]
sure.
