### ISSUE TITLE
Cannot Load Plugins On MacOS

### ISSUE THREAD

**Issue by MCJEModder2026** [rizinorg/cutter#3383]
**Environment information**
* Operating System:
* Cutter version:
* Obtained from:
  - [ ] Built from source
  - [x] Downloaded release from Cutter website or GitHub 
  - [ ] Distribution repository
* File format:

**Describe the bug**

```
ERROR: rz_sys_dlopen: error: /Users/<>/.local/lib/rizin/plugins/core_retdec.dylib (dlopen(/Users/<>/.local/lib/rizin/plugins/core_retdec.dylib, 0x0009): tried: '/Users/<>/.local/lib/rizin/plugins/core_retdec.dylib' (code signature in <D9D051E5-25F9-3F57-A203-1C0EEE0F809D> '/Users/<>/.local/lib/rizin/plugins/core_retdec.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs), '/System/Volumes/Preboot/Cryptexes/OS/Users/<>/.local/lib/rizin/plugins/core_retdec.dylib' (no such file), '/Users/<>/.local/lib/rizin/plugins/core_retdec.dylib' (code signature in <D9D051E5-25F9-3F57-A203-1C0EEE0F809D> '/Users/<>/.local/lib/rizin/plugins/core_retdec.dylib' not valid for use in process: mapping process and mapped file (non-platform) have different Team IDs))
```
**To Reproduce**

install rizin retdec and cutter retdec
it does not work
check log

**Expected behavior**
plugins work

**Screenshots**

**Additional context**

**Comment by karliss** [comment]
@TheKidThatCodes Could you clarify the version of macOS you are using and the CPU architecture

**Comment by MCJEModder2026** [comment]
whatever the latest version of macos on the m2 mac mini

**Comment by MCJEModder2026** [comment]
macos 15 or whatever it is

**Comment by karliss** [comment]
Could you try with the build from this PR https://github.com/rizinorg/cutter/actions/runs/11381269277?pr=3385 , scroll to the bottom there should be a download link?

You will probably have to rebuild the retdec plugin against this version of cutter/rizin assuming you previously built it for the 2.3.4 release.

**Comment by MCJEModder2026** [comment]
last time i tried downloading a artifact build it didnt let me run it because "could not verify if not virus" or smth like that

**Comment by MCJEModder2026** [comment]
stupid gatekeeper, i want to run virusus
