### ISSUE TITLE
Right-click menu item to color instruction background

### ISSUE THREAD

**Issue by s0i37** [rizinorg/cutter#444]
Hello.
I just want to suggest add opportunity make background-color for instruction in graph view/disassembly (like IDA).
It will be very fine if you implements this via "ecHi/ecHw" radare2 commands.
This is very need durring visual trace-analysis from another utils.
Thank you.

* [x] Right click color block
* [x] Right click instruction line.

**Comment by xarkes** [comment]
You mean that you need this with a script through the API or you also need to do this manually with a mouse?

**Comment by xarkes** [comment]
Manually tried calling `ecHi` and `ecHw` from console and then View->Refresh Contents, it looks like there is something wrong with disasm parsing.

**Comment by s0i37** [comment]
Can you get rgb-code of instruction in cutter?

**Comment by xarkes** [comment]
I don't think so but that can be quickly implemented I believe.

**Comment by s0i37** [comment]
I have a crash after set "e scr.html=true" and View->Refresh Contents.

**Comment by s0i37** [comment]
Hello.
After last release a color highlighting has worked. But not everywhere...
![temp](https://user-images.githubusercontent.com/22872513/44486002-d597b180-a66b-11e8-983a-cc2d837639c0.png)
I highlighted two instruction through "ecHi red" command.

**Comment by ITAYC0HEN** [comment]
probably would be implemented soon by @xarkes :)
Remember this issue when you'll push it

**Comment by xarkes** [comment]
My current solution doesn't use radare2 API.

**Comment by ITAYC0HEN** [comment]
The issue says "like". It doesn't matter how it's matter what. ecH are simply nice to have, but any solution is good :)

**Comment by ITAYC0HEN** [comment]
@xarkes is your solution supports highlight a specific instruction?

**Comment by xarkes** [comment]
Not it doesn't but it would work quite similarly if anyone wanted to do so.

**Comment by ITAYC0HEN** [comment]
@optizone you may want to look at this one as well. Can be combined with your solution via
Right click (on line, or when multi-lines are selected):
`Highlight -> Line(s) -> Color picker`

Right Click anywhere in the block:

`Highlight -> Block -> Color picker`

**Comment by ITAYC0HEN** [comment]
Highlighting block is already implemented by @optizone , now highlighting line should be trivial :)

**Comment by xarkes** [comment]
I wouldn't say trivial since the logic is a bit different :p

**Comment by s0i37** [comment]
I can highlight a line with cutter api?

**Comment by ITAYC0HEN** [comment]
Closed in #1879

**Comment by ITAYC0HEN** [comment]
reopening. @v3ctor said correctly, this isssue requested highlighting in disas view as well. Implemented in #1911

**Comment by USSCltd** [comment]
BTW, what about `ecHi` highlighting? It is more convenient because I can highlight everything with one command in console window withour writing python scripts. For example `ecHi green @@.drcov.log`
Now it works but only if instruction has one color.

**Comment by ITAYC0HEN** [comment]
Line coloring in Cutter isn't going through `ecH`, we implemented our own logic for this to support the widgets we use. We're very close to a solution, there's only this PR that @v3ctor needs to finish :) Or anybody else who is willing to push the last changes. Maybe you, @USSCltd ?

**Comment by USSCltd** [comment]
It seems `ecHi` works but not good. Are you going to remove this completely?

**Comment by ITAYC0HEN** [comment]
How are you using ecHi in Cutter? because as far as I know, we never
supported this command since it is a terminal-based command. We in Cutter
color the blocks and lines in the graph view by using our own
implementation of coloring. Check the context menu of graph view to see how
it looks like when coloring blocks.

if you use the "ec" commands from the integrated console, we do not support
it and it somewhat hacky :)

**Comment by USSCltd** [comment]
Just `ecHi color @offset`.
Ok.
I see what you implements `cutter.BasicBlockHighlighter()` for highlighting basic block. But I can see for instruction.
```
dir(cutter)
['BasicBlockHighlighter', 'Configuration', 'CutterCore', 'CutterDockWidget', 'CutterPlugin', 'MainWindow', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'cmd', 'cmdj', 'core', 'json', 'message', 'refresh', 'version']
```
Is it implemented in python?

**Comment by ITAYC0HEN** [comment]
Check out this pull request :)
https://github.com/radareorg/cutter/pull/1911

**Comment by karliss** [comment]
Replacing BasicInstructionHighlighter and BasicBlockHighlighter with `ecHi` and `afbc` would be preferrable. Some things that need to be imrpoved in r2 wor ecHi to work well in Cutter
* ansi code to html color converting code. Currently it doesn't take html tag nesting limitations into account sometimes resulting in broken look as can bee seen in screenshot above.
* Saved color annotations should be stored using output independent way. Currently it is stored as terminal escape code which results in bad API. It should probably be stored as uint32 instead.

**Comment by karliss** [comment]
First part fixing ansi code to html converter is done https://github.com/radareorg/radare2/commit/adc2fb525d9d93e1738ebe40a0548fd0f99e811f .

**Comment by s0i37** [comment]
It seems it's already working)
